### DISCUSSION TITLE
Swarm Mode (with multiple nodes)

### DISCUSSION THREAD

**Discussion by tjhoff** [offen/docker-volume-backup#290] [Q&A]
Hello! Wondering if anyone can give me some pointers on running this tool in a multi-node swarm. I've read through the docs (specifically mentioning [swarm mode](https://offen.github.io/docker-volume-backup/how-tos/use-with-docker-swarm.html)) but didn't find any exact answers.

Given that volumes exist only on the docker node where a service replica is running, and service replicas can be assigned to whatever nodes have availability (and meet constraints) - what could I do to use this tool to effectively scale backups of service volumes? 

A minimal example of a stack that shows this behavior is below:
```
version: "3.8"

services:
  foo:
    image: busybox
    command: "sleep infinity"
    volumes:
      - shared_volume:/home/foo

  bar:
    image: busybox
    command: "sleep infinity"
    volumes:
      - shared_volume:/home/bar

volumes:
  shared_volume:
```

Assuming I have nodes `a` and `b` in the swarm, I saw that the `foo` service container was replicated on node `a`, and the `bar` service container was replicated on node `b`.

I can think of a few (non-optimal) ways to do this
- use global replication for the backup task (scaling unfortunately would be `N` services x `M` nodes)
- use node hostname constraints for both the deployed services and the backup service (not super helpful for scaling services) 
- use `swarm-cronjob` to run global replicas of `docker-volume-backup` that dynamically scrapes and backs up volumes based on a whitelist (whitelist has to be maintained)
- run a system service outside of docker on each node (loses the "just works" aspect of docker swarm stack deployment and node onboarding)

I realize this gets pretty close into the evergreen issue of **Docker Swarm shared volumes**, but looking for ways around this for my current infrastructure. 

Appreciate any help - really interested in this tool!
