### DISCUSSION TITLE
BACKUP_STOP_CONTAINER_LABEL not stopping container when referencing an env variable

### DISCUSSION THREAD

**Discussion by cxhamilton** [offen/docker-volume-backup#321] [Q&A] [answered]
I chose to externalize all of my docker-volume-backup configuration parameters to an external docker env file. My goal is to have a consistent approach to my backups, having only to change one file if I want to make a holistic change. I only need to set `BACKUP_NAME` (my made-up variable) for each specific container, and everything else is handled by reference.

This approach works perfectly, save for docker-volume-backup stopping the container. I've tried setting `BACKUP_STOP_CONTAINER_LABEL` to `${BACKUP_NAME}` and `$${BACKUP_NAME}` to no avail. The backup happens and the backup files are rotated, but the container is never stopped (or restarted).

I'm honestly unsure if this is a bug, an unsupported feature, or my understanding docker. 

Here are the important bits from my configuration files:

docker-compose.yaml

```
services:
    plex:
        ...
        labels:
            - docker-volume-backup.stop-during-backup=plex

    plex-backup:
        container_name: plex-backup
        image: offen/docker-volume-backup:latest
        environment:
            - BACKUP_NAME=plex
            - BACKUP_CRON_EXPRESSION=${BACKUP_CRON_EXPRESSION}
            - BACKUP_ARCHIVE=${BACKUP_ARCHIVE}
            - BACKUP_FILENAME_EXPAND=${BACKUP_FILENAME_EXPAND}
            - BACKUP_FILENAME=${BACKUP_FILENAME}
            - BACKUP_LATEST_SYMLINK=${BACKUP_LATEST_SYMLINK}
            - BACKUP_PRUNING_PREFIX=${BACKUP_PRUNING_PREFIX}
            - BACKUP_RETENTION_DAYS=${BACKUP_RETENTION_DAYS}
            - BACKUP_STOP_CONTAINER_LABEL=${BACKUP_STOP_CONTAINER_LABEL}
            - BACKUP_EXCLUDE_REGEXP=${BACKUP_EXCLUDE_REGEXP}
            - NOTIFICATION_URLS=${NOTIFICATION_URLS}
            - NOTIFICATION_LEVEL=${NOTIFICATION_LEVEL}
        volumes:
            ...
        depends_on:
            - plex
        restart: unless-stopped
```	
	
external.env

```
BACKUP_CRON_EXPRESSION=0 2 * * *
BACKUP_ARCHIVE=/archive
BACKUP_FILENAME_EXPAND=true
BACKUP_FILENAME=$${BACKUP_NAME}_%Y%m%d%H%M%S.tar.gz
BACKUP_LATEST_SYMLINK=$${BACKUP_NAME}.latest.tar.gz
BACKUP_PRUNING_PREFIX=$${BACKUP_NAME}_
BACKUP_RETENTION_DAYS=30
BACKUP_STOP_CONTAINER_LABEL=$${BACKUP_NAME}
BACKUP_SOURCES=/backup
BACKUP_EXCLUDE_REGEXP=\.log$
NOTIFICATION_URLS=pushover://shoutrrr:<APP_KEY>@<USER_KEY>/?priority=1
NOTIFICATION_LEVEL=error
```

Any support or suggestions would be much appreciated.

**Comment by m90** [comment]
Do you mount the host's docker socket into the backup container? I.e. does your list of `volumes`  contain the following line

```
- /var/run/docker.sock:/var/run/docker.sock:ro
```

**Reply by cxhamilton** [reply]
Yes. Here's the full docker-compose definition for the container:

```
    plex-backup:
        container_name: plex-backup
        image: offen/docker-volume-backup:latest
        environment:
            - BACKUP_NAME=plex
            - BACKUP_CRON_EXPRESSION=${BACKUP_CRON_EXPRESSION}
            - BACKUP_ARCHIVE=${BACKUP_ARCHIVE}
            - BACKUP_FILENAME_EXPAND=${BACKUP_FILENAME_EXPAND}
            - BACKUP_FILENAME=${BACKUP_FILENAME}
            - BACKUP_LATEST_SYMLINK=${BACKUP_LATEST_SYMLINK}
            - BACKUP_PRUNING_PREFIX=${BACKUP_PRUNING_PREFIX}
            - BACKUP_RETENTION_DAYS=${BACKUP_RETENTION_DAYS}
            - BACKUP_STOP_CONTAINER_LABEL=${BACKUP_STOP_CONTAINER_LABEL}
            - BACKUP_EXCLUDE_REGEXP=${BACKUP_EXCLUDE_REGEXP}
            - NOTIFICATION_URLS=${NOTIFICATION_URLS}
            - NOTIFICATION_LEVEL=${NOTIFICATION_LEVEL}
        volumes:
            - config:${BACKUP_SOURCES}:ro
            - ${ARCHIVE_PATH}:${BACKUP_ARCHIVE}
            - /etc/localtime:/etc/localtime:ro
            - /etc/TZ:/etc/timezone:ro
            - /var/run/docker.sock:/var/run/docker.sock:ro
        depends_on:
            - plex
        restart: unless-stopped
```

It is also important to note:

- If I set `BACKUP_STOP_CONTAINER_LABEL=plex`, the container is stopped (and restarted). 
- If I set `BACKUP_STOP_CONTAINER_LABEL=${BACKUP_NAME}` in docker-compose.yml, the container is not stopped.
- If I set `BACKUP_STOP_CONTAINER_LABEL=${BACKUP_STOP_CONTAINER_LABEL}` in docker-compose.yml **_and_** set `BACKUP_STOP_CONTAINER_LABEL=${BACKUP_NAME}` in environment.env, the container is not stopped.
