### DISCUSSION TITLE
What is the best way to run a command in the `offen/docker-volume-backup` container before creating a backup?

### DISCUSSION THREAD

**Discussion by ottobolyos** [offen/docker-volume-backup#504] [Q&A]
I am using using [`timescale/timescaledb-ha`](https://hub.docker.com/r/timescale/timescaledb-ha) which runs PostgreSQL and all related commands as `postgres` user which has UID/GID set to `1000` (it is a non-root, non-system user). This causes an issue, as `docker-volume-backup` runs all commands are `root` , therefore everytime it creates a backup, the files are root-owned and `pg_dumpall` cannot access/overwrite the files in a subsequent backup.

Now, this can be easily worked around by running `chown -R 1000:1000 /backup` in the `docker-volume-backup` container before actually creating the backup. However, what is the best way to accomplish this?

Note that ATM I am using `offen/docker-volume-backup:v2.25.1` (set up by a former colleague) and I use the backup label on the database container to defined the backup command:

```bash
"docker-volume-backup.exec-pre=/bin/sh -c 'pg_dumpall -U $PGUSER --clean --file /home/postgres/pgdata/backup/dumpall.sql'"
```

As that `docker-volume-backup` version still uses external `cron`, I could bind-mount `/var/spool/cron/crontabs/root` and change the ownership of `/backup` before running `backup` (i.e. `0 1 * * * chown -R 1000:1000 /backup && backup 2>&1`), I’d like to have a kind of confirmation if this will work and is the best solution from your PoV.

Thank you in advance! :pray:

**Comment by m90** [comment]
Is there anything that keeps you from updating the Image version? Newer versions support running as non-root https://offen.github.io/docker-volume-backup/how-tos/use-as-non-root.html

**Reply by ottobolyos** [reply]
Thanks for replay, @m90! :pray:

Well, there is nothing that keeps me from updating the image version.

Are there any configuration changes between `v2.25.1` and `v2.43.0`? Has the default backup path in container changed fom `/backup` to `/backup/data`? Could you look at the following Docker Compose snippet whether you see something that needs to be updated please? :pray:

<details>
  <summary>Docker Compose snippet</summary>

```yaml
services:
  backup:
    container_name: backup
    environment:
      AWS_ACCESS_KEY_ID: $key_id
      AWS_ENDPOINT: $endpoint
      AWS_S3_BUCKET_NAME: $bucket
      AWS_SECRET_ACCESS_KEY: $access_key
      BACKUP_CRON_EXPRESSION: '0 1 * * *'
      BACKUP_FILENAME: 'backup-%Y-%m-%dT%H-%M-%S.tar.gz'
      BACKUP_PRUNING_PREFIX: 'backup-'
      BACKUP_RETENTION_DAYS: 3
      NOTIFICATION_LEVEL: error
      NOTIFICATION_URLS: $slack_hook
    image: offen/docker-volume-backup:v2.43.0
    logging:
      options:
        max-size: 20m
    networks:
      - net
    restart: always
    user: 1000:1000
    volumes:
      - $volumes/backup:/archive:rw
      - backup:/backup
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
  postgres:
    container_name: postgres
    image: timescale/timescaledb-ha:pg17.2-ts2.17.2
    labels:
      docker-volume-backup.archive-pre: /bin/sh -c 'pg_dumpall -U $PGUSER --clean --file
        /home/postgres/pgdata/backup/dumpall.sql'
    networks:
      - net
    volumes:
      - backup:/home/postgres/pgdata/backup
      # ...
    # ...
networks:
  net:
    name: net
volumes:
  backup:
```

</details>
