### DISCUSSION TITLE
Backing up multiple containers

### DISCUSSION THREAD

**Discussion by JTRedEye26** [offen/docker-volume-backup#507] [Q&A]
I just want to double check that I have my configuration right before I fire this off. I have a docker compose yml that has 9 containers that I would like to setup. I read the docs and didn't see any examples where is shows off what backing up multiple containers should look like. I saw the BACKUP_SOURCES variable but not sure if I should use it here. This is what I got for the backup container and I am using docker-volume-backup.stop-during-backup=true labels on all the containers that need backed up. If I understand the docs this should create one backup file that contains all my separated volumes in it daily and then prune the old backup files that are older the 14 days. Also there shouldn't be any issues with backing up the volumes to a mounted smb share right?

```
backup:
    image: offen/docker-volume-backup:v2.42.0
    restart: always
    environment:
      BACKUP_FILENAME: backup-%Y-%m-%d.tar.gz
      BACKUP_CRON_EXPRESSION: "0 2 * * *"
      BACKUP_PRUNING_PREFIX: backup-
      BACKUP_RETENTION_DAYS: '14'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/server/dockerVolumesBackups:/archive
      
      #sets timezone
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

      #volumes to backup
      - prowlarr:/backup/prowlarr-backup:ro
      - qbittorrent:/backup/qbittorrent-backup:ro
      - radarr:/backup/radarr-backup:ro
      - sonarr:/backup/sonarr-backup:ro
      - readarr:/backup/readarr-backup:ro
      - jellyfin:/backup/jellyfin-backup:ro
      - jellyseerr:/backup/jellyseerr-backup:ro
      - pihole:/backup/pihole-backup:ro
      - kavita:/backup/kavita-backup:ro
```
