### ISSUE TITLE
Unable to trigger a backup

### ISSUE THREAD

**Issue by rwanito** [offen/docker-volume-backup#122]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

* **What is the current behavior?**
I want to trigger a backup in my swarm cluster.

Here my compose :
```yaml
  backup:
    image: offen/docker-volume-backup:v2.19.0
    deploy:
      resources:
        limits:
          memory: 25M
      restart_policy:
        condition: on-failure
    environment:
      AWS_ENDPOINT: ...
      AWS_S3_BUCKET_NAME: ...
      AWS_ACCESS_KEY_ID: ...
      AWS_SECRET_ACCESS_KEY:...
      AWS_S3_PATH: ...
      AWS_STORAGE_CLASS: ...
      NOTIFICATION_URLS: ....
    volumes:
      - traefik-public-certificates:/backup/traefik-public-certificates:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
```

And the error I get is  : 

```bash
erwan@server:~$ docker exec traefik_backup.1.IDIDIDIDID backup
panic: newScript: error creating sender: error initializing router services: unknown service ""

goroutine 1 [running]:
main.main()
	/app/cmd/backup/main.go:13 +0x41e

```

Any ideas ?

Thank you for your work !
