### ISSUE TITLE
Question on backing up?

### ISSUE THREAD

**Issue by killmasta93** [offen/docker-volume-backup#127]
Hi
I wanted to see if someone could shed some light, currently i need to backup and restore my wordpress docker-compose 
i was looking at the read me section 
i see lots of examples but not sure if i would need to add the offen docker imagine in the docker compose?
or i would need to create another docker-compose to backup the wordpress container?

Thank you 

```
version: '3.9'

services:
  # Database
  db:
    image: mysql:8.0
    volumes:
      - /wordpress/db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: mypassword
    networks:
      - wpsite
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8083:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: mypassword
    networks:
      - wpsite
  # Wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - '8084:80'
    restart: always
    volumes:
      - /wordpress/html:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: mypassword
    networks:
      - wpsite
networks:
  wpsite:
volumes:
  db_data:
  html:
```

**Comment by m90** [comment]
> or i would need to create another docker-compose to backup the wordpress container

There's no definitive answer to this question as both approaches would work, however adding an additional service based off `offen/docker-volume-backup` in your existing compose setup is probably the easiest way to move forward.

See the example here: https://github.com/offen/docker-volume-backup#recurring-backups-in-a-compose-setup where `volume-consumer` are the other services you are defining.

It might also be helpful to have a look at the setups this repo is using for testing: https://github.com/offen/docker-volume-backup/tree/main/test

**Comment by killmasta93** [comment]
Thank you so much for the reply,
So after reading a while the documentation i tried to adapt which came to conclusion this docker compose

```
version: '3.9'

services:
  # Database
  db:
    image: mysql:8.0

    volumes:
      - /wordpress/db_data:/var/lib/mysql
    labels:
      # This means the container will be stopped during backup to ensure
      # backup integrity. You can omit this label if stopping during backup
      # not required.
      - docker-volume-backup.stop-during-backup=true
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: mypassword
    networks:
      - bw-services
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8083:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: mypassword
    networks:
      - bw-services
  # Wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - '8084:80'
    restart: always
    volumes:
      - /wordpress/html:/var/www/html
    labels:
      # This means the container will be stopped during backup to ensure
      # backup integrity. You can omit this label if stopping during backup
      # not required.
      - docker-volume-backup.stop-during-backup=true
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: mypassword
    networks:
      - bw-services


  backup:
    image: offen/docker-volume-backup:v2
    environment:
      BACKUP_FILENAME: backup-%Y-%m-%dT%H-%M-%S.tar.gz
      BACKUP_LATEST_SYMLINK: backup-latest.tar.gz
    volumes:
      - data:/backup/my-app-backup:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${HOME}/backups:/archive

networks:
  bw-services:
volumes:
  data:
  db_data:
  html:
```
then i ran 
```
root@homelab:~# docker exec deepsight_backup_1 backup
time="2022-07-16T04:21:34Z" level=info msg="Stopping 2 container(s) labeled `docker-volume-backup.stop-during-backup=true` out of 12 running container(s)."
time="2022-07-16T04:21:38Z" level=info msg="Created backup of `/backup` at `/tmp/backup-2022-07-16T04-21-34.tar.gz`."
time="2022-07-16T04:21:40Z" level=info msg="Restarted 2 container(s) and the matching service(s)."
time="2022-07-16T04:21:40Z" level=info msg="Stored copy of backup `/tmp/backup-2022-07-16T04-21-34.tar.gz` in local archive `/archive`."
time="2022-07-16T04:21:40Z" level=info msg="Created/Updated symlink `backup-latest.tar.gz` for latest backup."
time="2022-07-16T04:21:40Z" level=info msg="Removed tar file `/tmp/backup-2022-07-16T04-21-34.tar.gz`."
time="2022-07-16T04:21:40Z" level=info msg="Finished running backup tasks."
```
which created backup on my host in /backups

now i would need restore the container on another host, i was reading the part of the restore but im a bit lost 

in the backup folder i have two files would i send those files to the other host? 
```
root@homelab:/backups# ls -lah
total 12K
drwxr-xr-x  2 root root 4.0K Jul 15 23:21 .
drwxr-xr-x 26 root root 4.0K Jul 15 23:19 ..
-rw-r--r--  1 root root  130 Jul 15 23:21 backup-2022-07-16T04-21-34.tar.gz
lrwxrwxrwx  1 root root   33 Jul 15 23:21 backup-latest.tar.gz -> backup-2022-07-16T04-21-34.tar.gz
```


Thank you

**Comment by m90** [comment]
I'm not sure what you mean by "sending to the other host". This probably depends on your setup and where you are storing the archives and is hard to answer in this context.

Information about restoring the backups themselves is found here https://github.com/offen/docker-volume-backup#restoring-a-volume-from-a-backup

**Comment by killmasta93** [comment]
Thanks for the reply, i was reading that step but could not get it working, 
these were the steps i took from the guide 

my question how come i need to create a temp container if already have the container of wordpress to restore?


```
root@homelab:/backups# tar -C /tmp -xvf backup-latest.tar.gz 
tar: Removing leading `/' from member names
/backup
/backup/my-app-backup
root@homelab:/backups# ls
backup-2022-07-16T04-21-34.tar.gz  backup-latest.tar.gz
root@homelab:/backups# docker run -d --name temp_restore_container -v data:/backup_restore alpine
Unable to find image 'alpine:latest' locally
latest: Pulling from library/alpine
2408cc74d12b: Already exists 
Digest: sha256:686d8c9dfa6f3ccfc8230bc3178d23f84eeaf7e457f36f271ab1acc53015037c
Status: Downloaded newer image for alpine:latest
fb7bc3bc64a85555fa0cb66e9a22dd41543b58fcf68e5742a36eab3300362e83
root@homelab:/backups# docker cp /tmp/backup/data-backup temp_restore_container:/backup_restore
lstat /tmp/backup/data-backup: no such file or directory
```

**Comment by m90** [comment]
Restoring backups is not really something this tool is responsible for, so there are many ways to do it, depending on your requirements and setup.

> my question how come i need to create a temp container if already have the container of wordpress to restore?

You don't necessarily need to create a temporary container, it's just one way to do it. If you look at the docs, it also has a "snapshot" style restore process that works without the temporary container.

As for the shell output you provide I notice one thing: when unpacking the archive, you create a directory called `/backup/my-app-backup`, however later on you try to copy `/backup/data-backup`. Could it be that you mixed up the directory names here?

**Comment by killmasta93** [comment]
hi again, so after a while i configured so it can be a volume instead a mount but im getting an error 

`failed to deploy a stack: In file '/data/compose/34/docker-compose.yml', volume must be a mapping, not an array. : exit status 1`

```
version: '3.9'

services:
  # Database
  db2:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: mypassword
    networks:
      - wpsite2
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db2
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8099:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: mypassword
    networks:
      - wpsite2
  # Wordpress
  wordpress:
    depends_on:
      - db2
    image: wordpress:latest
    ports:
      - '8089:80'
    restart: always
    volumes:
      - html:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db2:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: mypassword
    networks:
      - wpsite2
networks:
  wpsite2:
  
backup:
    # In production, it is advised to lock your image tag to a proper
    # release version instead of using `latest`.
    # Check https://github.com/offen/docker-volume-backup/releases
    # for a list of available releases.
    image: offen/docker-volume-backup:latest
    restart: always
    environment:
      BACKUP_FILENAME: backup-%Y-%m-%dT%H-%M-%S.tar.gz
      BACKUP_LATEST_SYMLINK: backup-latest.tar.gz
   
volumes:
      - db_data:/backup/my-app-backup:ro
      - html:/backup/my-app2-backup:ro
      # Mounting the Docker socket allows the script to stop and restart
      # the container during backup. You can omit this if you don't want
      # to stop the container. In case you need to proxy the socket, you can
      # also provide a location by setting `DOCKER_HOST` in the container
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # If you mount a local directory or volume to `/archive` a local
      # copy of the backup will be stored there. You can override the
      # location inside of the container by setting `BACKUP_ARCHIVE`.
      # You can omit this if you do not want to keep local backups.
      - /root:/archive      
db_data:
    driver: local-persist
    driver_opts:
      mountpoint: /testwp/data
html:
    driver: local-persist
    driver_opts:
      mountpoint: /testwp/www
```

**Comment by killmasta93** [comment]
just wanted to post back finally got it working with the backup configured correctly this was the docker compose 
thank you again for docker backup repo really nice work 

```
version: '3.9'

services:
  # Database
  db:
    image: mysql:8.0

    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: thepassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: thepassword
    networks:
      - wpnet
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8023:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: thepassword
    networks:
      - wpnet
  # Wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - '8024:80'
    restart: always
    volumes:
      - html:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: thepassword
    networks:
      - wpnet
  backup:
    # In production, it is advised to lock your image tag to a proper
    # release version instead of using `latest`.
    # Check https://github.com/offen/docker-volume-backup/releases
    # for a list of available releases.
    image: offen/docker-volume-backup:latest
    restart: always
    environment:
      BACKUP_FILENAME: backup-%Y-%m-%dT%H-%M-%S.tar.gz
      BACKUP_LATEST_SYMLINK: backup-latest.tar.gz
    volumes:
      - db_data:/backup/db_data:ro
      - html:/backup/html:ro
      # Mounting the Docker socket allows the script to stop and restart
      # the container during backup. You can omit this if you don't want
      # to stop the container. In case you need to proxy the socket, you can
      # also provide a location by setting `DOCKER_HOST` in the container
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # If you mount a local directory or volume to `/archive` a local
      # copy of the backup will be stored there. You can override the
      # location inside of the container by setting `BACKUP_ARCHIVE`.
      # You can omit this if you do not want to keep local backups.
      - ${HOME}/backups:/archive      
networks:
  wpnet:
volumes:
  db_data:
    driver: local-persist
    driver_opts:
      mountpoint: /tempwp/db_data
  html:
    driver: local-persist
    driver_opts:
      mountpoint: /tempwp/html
```
