### ISSUE TITLE
Support for filebase.com S3

### ISSUE THREAD

**Issue by mazz** [offen/docker-volume-backup#13]
Can you add support for filebase.com S3 bucket access? When I tried:

`AWS_ENDPOINT: "s3://us-east-1.s3.filebase.com"`

I got the startup error:
`backup_1  | mc: <ERROR> Invalid URL. URL `https://s3://us-east-1.s3.filebase.com` for MinIO Client should be of the form scheme://host[:port]/ without resource component.`

**Comment by m90** [comment]
You need to omit the `s3://` protocol (which I think is an aws cli specific thing only) from the endpoint and use `s3.filebase.com` instead. See: https://docs.filebase.com/platform-overview/service-endpoints

**Comment by m90** [comment]
I added a note about this in the README.

**Comment by mazz** [comment]
@m90 thanks that helped and I have backups being written to filebase S3 successfully. Here are my settings for anyone else with an issue with filebase(docker-compose.yml):

```
  backup:
  ...
    environment:
    ...
            AWS_ACCESS_KEY_ID: "secret"
            AWS_SECRET_ACCESS_KEY: "secret"
            AWS_S3_BUCKET_NAME: "my-filebase-bucket"
            AWS_ENDPOINT: "s3.filebase.com"
```

My bucket settings were `StorJ` and `Private`
