### ISSUE TITLE
Backup multiple app volumes via docker compose config?

### ISSUE THREAD

**Issue by bverkron** [offen/docker-volume-backup#158]
**What are you trying to do?**
I would like to be able to backup multiple app container volumes by configuring the docker-compose for the docker-volume-backup container. I would prefer not to have to setup configuration files on the host (as per `  - ./configuration:/etc/dockervolumebackup/conf.d`) and defined everything in the compose file to make it more "portable". i.e. if I need to move this to another docker host I don't want to have to manually setup things like this on the host.

**What is your current configuration?**
```
services:
  semaphore:
    ports:
      - 3000:3000
    image: semaphoreui/semaphore:latest
    container_name: semaphore-bolt
    environment:
      ...
    volumes:
      - home:/home/semaphore
      - etc:/etc/semaphore
      - lib:/var/lib/semaphore
    restart: unless-stopped      

  backup:
    image: offen/docker-volume-backup:latest
    environment:
      BACKUP_CRON_EXPRESSION: "0 1 * * *"
      BACKUP_FILENAME: semaphore-backup-%Y-%m-%dT%H-%M-%S.tar.gz
      BACKUP_LATEST_SYMLINK: semaphore-backup-latest.tar.gz
      # Env vars here to configure multiple volume backups?
    volumes:
      - etc:/backup/etc:ro # ?
      - lib:/backup/lib:ro # ?   
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /nfs/server_name/backups/semaphore/:/archive/

volumes:
  home:
  etc:
  lib:
```

**Log output**
N/A

**Additional context**
The documentation says "If a configuration value is set both in the global environment as well as in the config file, the config file will take precedence." which makes it sound like environment variables can be set in docker-compose to control this but it's unclear if I'm interpreting the doc correctly and if so how to set those up.
