### ISSUE TITLE
gpg decryption not working

### ISSUE THREAD

**Issue by bverkron** [offen/docker-volume-backup#162]
**What are you trying to do?**
I am testing the gpg encryption feature and am trying to decrypt the backup. The first time I attempted to decrypt I was prompted for the password, pasted it in (from password manager), and it gave an error (didn't capture it, might have been different than below). All subsequent times I attempt to decrypt I get this:

```
$ gpg -o backup.tar.gz -d portainer-backup-2022-10-15T20-11-55.tar.gz.gpg
gpg: AES.CFB encrypted session key
gpg: gcry_kdf_derive failed: Invalid data
gpg: encrypted with 1 passphrase
gpg: decryption failed: Bad session key
```

**What is your current configuration?**
```yaml
services:
  backup:
    # https://github.com/offen/docker-volume-backup#readme
    image: offen/docker-volume-backup:latest
    container_name: $APP_NAME-backup
    depends_on:
      - "$APP_NAME"
    environment:
      BACKUP_CRON_EXPRESSION: "0 1 * * *"
      BACKUP_FILENAME: $APP_NAME-backup-%Y-%m-%dT%H-%M-%S.tar.gz
      BACKUP_PRUNING_PREFIX: $APP_NAME-backup-
      BACKUP_RETENTION_DAYS: 14
      NOTIFICATION_URLS: smtp://**********:$EMAIL_PASSWORD@smtp.gmail.com:587/?fromAddress=master_control@home&toAddresses=*********            
      NOTIFICATION_LEVEL: info
      GPG_PASSPHRASE: $GPG_PASSPHRASE
    volumes:
      # Standard config    
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /mnt/ReplicateOut_master_control/backups/$APP_NAME/:/archive/
      # Customize for app
      - /home/master/portainer/mount_data/:/backup/data/:ro
    restart: unless-stopped 
```

**Log output**
See gpg error output above

**Additional context**
This is the gpg version I'm running on my Mac.
```
$ gpg --version
gpg (GnuPG) 2.3.8
libgcrypt 1.10.1
```
Sort of grasping at straws here but this stackoverflow post indicates it might be a version issue. Though I'm not sure why a newer version of gpg would not be able to decrypt files created by older versions. I could see the other way around though.

https://stackoverflow.com/a/30934702

I tried to determine the version of gpg used in the backup container but I cannot find it under the same command name
```
~ # gpg
sh: gpg: not found
```
