### ISSUE TITLE
SMTP not working?

### ISSUE THREAD

**Issue by bpawel-bclub** [offen/docker-volume-backup#169]
**What are you trying to do?**
Trying to configure SMTP to send emails of a successful backup.

**What is your current configuration?**
Tried both old and new methods: 
`NOTIFICATION_LEVEL="info"`

### New
`NOTIFICATION_URLS="smtp://username:password@amazon_ses_server:587/?fromAddress=backup@example.org&toAddresses=email@example.org"`

### Old
`EMAIL_NOTIFICATION_RECIPIENT="email@example.org"`
`EMAIL_NOTIFICATION_SENDER="backup@example.org"`
`EMAIL_SMTP_HOST="amazon_ses_server"`
`EMAIL_SMTP_PASSWORD="password"`
`EMAIL_SMTP_USERNAME="username"`
`EMAIL_SMTP_PORT="587"`

**Log output**
`offen_1   | time="2022-12-03T12:03:02Z" level=warning msg="SMTP for transactional email is not configured right now, mail delivery will be unreliable"`
`offen_1   | time="2022-12-03T12:03:02Z" level=warning msg="Refer to the documentation to find out how to configure SMTP"`

**Additional context**
The backup runs as expected, and the file gets uploaded to S3. However, no email is sent despite the level set to "info". I first tried the `NOTIFICATION_URLS`, and when it didn't work the old way, also not successful.

Thanks!

**Comment by m90** [comment]
I'm a bit confused as the log ouptut you are quoting seems to be coming from `offen/offen` which is not connected to the backup tool sending out emails in any way. Are you sure you are configuring a container off the correct image?

Your configuration looks correct, and SMTP is known to be working well in recent versions, so right now I'd need more info to debug this. Could you maybe share your full setup?

**Comment by bpawel-bclub** [comment]
Thanks for replying. Here is my configuration:

## docker-compose.yml


```
version: '3'

services:
  offen:
    image: offen/offen:latest
    volumes:
      - db:/var/opt/offen
    labels:
      - docker-volume-backup.stop-during-backup=true

  backup:
    image: offen/docker-volume-backup:v1.0.2
        # Ideally, those values should go into an `env` file or Docker secrets
        # as they contain credentials. It's easier to spell them out here
        # in the context of this tutorial though.
    env_file: 
      - .env
    volumes:
            # This allows the tool to stop and restart all
            # containers labeled as docker-volume-backup.stop-during-backup
      - /var/run/docker.sock:/var/run/docker.sock:ro
            # All volumes mounted to /backup/<some-name> will be backed up
      - db:/backup/offen-db:ro

volumes:
  db:
```

## .env file


```
BACKUP_CRON_EXPRESSION="03 12 * * *"
BACKUP_FILENAME="offen-db-%Y-%m-%dT%H-%M-%S.tar.gz"

BACKUP_RETENTION_DAYS="7"

# Credentials for your storage backend
AWS_ACCESS_KEY_ID=#####
AWS_SECRET_ACCESS_KEY=#####
AWS_S3_BUCKET_NAME=#####

# If given, backups are encrypted using GPG
# GPG_PASSPHRASE="<SOME_KEY>"

# SMTP
NOTIFICATION_LEVEL="info"
# NOTIFICATION_URLS="smtp://username:password@amazon_ses_server:587/?fromAddress=backup@example.org&toAddresses=email@example.org"

EMAIL_NOTIFICATION_RECIPIENT="email@example.org"
EMAIL_NOTIFICATION_SENDER="backup@example.org"
EMAIL_SMTP_HOST="amazon_ses_server"
EMAIL_SMTP_PASSWORD="password"
EMAIL_SMTP_USERNAME="username"
EMAIL_SMTP_PORT="587"
```
