### ISSUE TITLE
Error using env_file: backup.env 

### ISSUE THREAD

**Issue by acappelletti** [offen/docker-volume-backup#174]
Hi all,
I would like to load an external env/config file, without insert all the needed ENV variables... but I got some problems.
I use to map from a dir outside my docker area all my .yaml files.

It's not clear to me how to map the external file (/etc/docker/monitoring-sql/docker-volume-backup/backup.env).
The online example show me to use in .env (which I've never used before).
I'm using a docker-compose solution into my portainer (all the env variable are insidet portainer)

The error is: "no dir of file in /data/compose/88/backup.env"
Is there any internal path that I can override with the external config file?
This is the code:

```
#=============================================================================
  docker-volume-backup:
    image: ${dockervolumebackup}
    restart: always
    env_file: backup.env
    volumes:
      - postgres-storage:/backup/postgres-storage:ro
      - grafana-postgres-storage:/backup/grafana-postgres-storage:ro
      - pgadmin-storage:/backup/pgadmin-storage:ro
      - /etc/docker/monitoring-sql/docker-volume-backup/backup.env:/data/compose/88/backup.env

      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/docker/monitoring-sql/docker-volume-backup:/archive
    environment:
     BACKUP_CRON_EXPRESSION: "0 * * * *"
#============================================================================= 
```

Thanks Alen
