### ISSUE TITLE
134 bytes long backup files.

### ISSUE THREAD

**Issue by staminna** [offen/docker-volume-backup#179]
**What are you trying to do?**
A simple backup. When I run docker-compose,  when it bootstraps and when I stop the containers, I can see the bind volume backup activity but all my files are 134 bytes tg.gz long are corrupted. I am on MacOS Monterey latests with M1 Pro chip.

**What is your current configuration?**
Add the full configuration you are using. Please redact out any real-world credentials.

```
version: '3'
services:
  database:
    container_name: pflocal-postgresql-data
    image: postgis/postgis:13-master
    volumes:
      - type: bind
        source: ./pflocal-postgresql-data/database
        target: /var/lib/postgresql/data
...
  backup:
    image: offen/docker-volume-backup:v2
    environment:
      BACKUP_CRON_EXPRESSION: "2 * * * *"
      BACKUP_FILENAME: pflow-jorge-backup-%Y-%m-%dT%H-%M-%S.tar.gz
      BACKUP_LATEST_SYMLINK: backup-latest.tar.gz
      BACKUP_RETENTION_DAYS: 6
    volumes:
      - pflocal-postgresql-data:/backup/my-app-backup:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${HOME}/backups:/archive

networks:
  directus:

volumes:
  pflocal-postgresql-data:
```

**Log output**
Provide the full log output of your setup.

**Additional context**
Add any other context or screenshots about the support request here.

Should you require more information, I'll be happy to provide it to you as soon as possible.

**Comment by m90** [comment]
Are the backup files corrupted or are they just empty? If they are corrupted, what's the error you are seeing when you try to untar them?

Looking at your configuration I can spot one issue: you do define a `pflocal-postgresql-data` volume and also mount it to be backed up, but then your Postgres container does not mount the volume, but a local path instead. If you want the local path to be backed up, you will have to mount the same directory instead of the unused volume.

**Comment by m90** [comment]
For reference, some tests also backup postgres, so you can have a look at the compose file here https://github.com/offen/docker-volume-backup/blob/main/test/ownership/docker-compose.yml to get an idea how this is supposed to be configured.

**Comment by staminna** [comment]
The tar.gz decompress without error but they contain only a folder "backup" with nothing inside. I deleted everything anyway it wasn't configured-

But I also need a bind mount on my local hard drive to make backups of the database records as it is easier to Git backup with code the current status of the database. 

I am using Postgres 13 master but it isn't backing up any file, despite its taking 10 seconds to compress a file on an M1 Pro and a 300MB uncompressed database. That is why I thought it was normal since the beginning but now could be normal but I can't find it anywhere looking even though I am looking at the example.

Here is my new compose file:

```
version: '3'
services:
  database:
    container_name: pflowlocal-postgresql-data
    image: postgis/postgis:13-master
    restart: unless-stopped

    labels:
      - docker-volume-backup.stop-during-backup=true
    volumes:
      - pflowlocal-postgresql-data:/var/lib/postgresql/data
      - type: bind
        source: ./pflowlocal-postgresql-data/database
        target: /var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'jorge'
      POSTGRES_PASSWORD: ''
      POSTGRES_DB: 'pflowlocal'

...
  backup:
    image: offen/docker-volume-backup:v2
    restart: always
    environment:
      BACKUP_FILENAME: pflow-backup.tar.gz
    volumes:
      - pflowlocal-postgresql-data:/backup/postgres:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./local:/archive

volumes:
  pflowlocal-postgresql-data:

```

**Comment by m90** [comment]
> The tar.gz decompress without error but they contain only a folder "backup" with nothing inside. 

You're currently backing up an empty volume, so this is expected.

> But I also need a bind mount on my local hard drive to make backups of the database records as it is easier to Git backup with code the current status of the database.

In that case, instead of mounting the volume into the backup container, mount the same bind mount. You can remove the volume entirely and just use the bind mount for both the database container as well as the backup one.

**Comment by staminna** [comment]
I still have the same problem. I was lucky haven't needed a backup yet.
I am using Directus and Postgres 13 latest version:

Here is my relevant compose.yml file:

```
version: '3'
services:
  database:
    container_name: pflowlocal-postgresql-data
    image: postgis/postgis:13-master
    restart: unless-stopped

    labels:
      - docker-volume-backup.stop-during-backup=true
    volumes:
      - type: bind
        source: ./pflowlocal-postgresql-data/database
        target: /var/lib/postgresql/data
    networks:
      - directus
backup:
    image: offen/docker-volume-backup:v2
    restart: always
    environment:
      BACKUP_CRON_EXPRESSION: "* * 1 * *"
      BACKUP_FILENAME: pflow-jorge-backup-%Y-%m-%dT%H-%M-%S.tar.gz
      BACKUP_RETENTION_DAYS: 5
    volumes:
      - pflowlocal-postgresql-data:/backup/postgres:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./local:/archive

networks:
  directus:

volumes:
  pflowlocal-postgresql-data:

```


Please let me know if you need more information
Best wishes, Jorge.
