### ISSUE TITLE
Setting BACKUP_CRON_EXPRESSION in env produces a parse error on latest version

### ISSUE THREAD

**Issue by eselskas** [offen/docker-volume-backup#185]
```
  db-backup:
    image: offen/docker-volume-backup:v2.25.1
    restart: always
    environment:
      - BACKUP_CRON_EXPRESSION="*/5 * * * *"
    volumes:
      - db:/backup/db-backup:ro
      - /var/docker/db_backups:/archive
```

Starting the container produces:

```
# docker-compose up db-backup
Starting e_db-backup_1 ... done
Attaching to e_db-backup_1
db-backup_1  | Installing cron.d entry with expression "*/5 * * * *".
db-backup_1  | Starting cron in foreground.
db-backup_1  | crond: crond (busybox 1.35.0) started, log level 8
db-backup_1  | crond: user root: parse error at "*/5
db-backup_1  | crond: user root: parse error at *"
```

Downgraded to v2.0.0 and it works fine

```
Status: Downloaded newer image for offen/docker-volume-backup:v2.0.0
db-backup_1  | Installing cron.d entry with expression "*/5 * * * *".
db-backup_1  | Starting cron in foreground.
```

**Comment by m90** [comment]
I did not confirm this, but I think what you are seeing is just a change in log verbosity (introduced in https://github.com/offen/docker-volume-backup/pull/120) and not a change in behavior. Does v2.0.0 even run backups on the given schedule?

I'm no expert in cron expressions but a good start would probably checking the limitations of BusyBox's cron implementation and whether it allows the expression you are passing here.

**Comment by m90** [comment]
Also, you might want to try to unquote your env var definition:

```yml
db-backup:
  image: offen/docker-volume-backup:v2.25.1
  restart: always
  environment:
    BACKUP_CRON_EXPRESSION: */5 * * * *
  volumes:
    - db:/backup/db-backup:ro
    - /var/docker/db_backups:/archive
```

to make sure you are not bitten by docker-compose passing a quoted string: https://github.com/docker/compose/issues/2854
