### ISSUE TITLE
Pruned files remain in a weird state on S3 compatible storage

### ISSUE THREAD

**Issue by nipser** [offen/docker-volume-backup#186]
Dear all,

first of all, thank you for your ongoing work on this project! I use it to create daily backups of my docker containers. Creating said backups works like a charm, however, when the container is pruning backups older than x days (I mainly use 7, but got this compose file with 1 day retention as a test), the files are set to being "hidden" inside the bucket instead of getting deleted. This is done by placing the backup archive into a folder together with a "[hide file](https://www.backblaze.com/b2/docs/b2_hide_file.html)".
![image](https://user-images.githubusercontent.com/11896495/217930273-4c5eeedc-e28f-4358-b651-954f01b33da5.png)
```First item (with the (2) *): folder, second item: hide file, third item: "deleted" backup archive file)```

I use the S3 compatible B2 bucket by [https://backblaze.com](https://backblaze.com). I opened a support case there and got some pretty informative replies from them (thanks again!), but still, I was unfortunately not able to solve my problem. Please check the screenshot of my support case with Backblaze at the end of this issue.
I know I could just create a lifecycle rule at Backblaze which would delete hidden files, but I'd prefer the container tidying up it's own trash as I consider that best practice.

I'm pretty sure I had it working in the past, but sadly can't remember when it stopped.
Has anyone seen this behavior before and could maybe give me a hint on what I'm doing wrong? :|

Thank you already for your time!
Best regards, 
  Thorben

---

**What is your current configuration?**
***docker-compose.yml***
```
version: "3.7"

services:

  backup:
      image: offen/docker-volume-backup:v2.25.1
      environment:
        BACKUP_FILENAME: traefik-backup-%Y-%m-%dT%H-%M-%S.tar.gz
        BACKUP_PRUNING_PREFIX: traefik-backup
        BACKUP_RETENTION_DAYS: 1
        AWS_ENDPOINT: s3.eu-central-003.backblazeb2.com
        AWS_ENDPOINT_PROTO: https
        AWS_S3_BUCKET_NAME: <redacted>
        AWS_ACCESS_KEY_ID: <redacted>
        AWS_SECRET_ACCESS_KEY: <redacted>
        BACKUP_CRON_EXPRESSION: "0 5 * * *"
        BACKUP_STOP_CONTAINER_LABEL: traefik-backup
      restart: always
      volumes:
        - .:/backup:ro
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - /etc/timezone:/
```

**Log output**
```
traefik-backup-backup-1  | time="2023-02-09T05:00:01+01:00" level=info msg="Created backup of `/backup` at `/tmp/traefik-backup-2023-02-09T05-00-01.tar.gz`."
traefik-backup-backup-1  | time="2023-02-09T05:00:02+01:00" level=info msg="Uploaded a copy of backup `/tmp/traefik-backup-2023-02-09T05-00-01.tar.gz` to bucket `docker-backup-bucket`."
traefik-backup-backup-1  | time="2023-02-09T05:00:03+01:00" level=info msg="Pruned 1 out of 2 remote backup(s) as their age exceeded the configured retention period of 1 days."
traefik-backup-backup-1  | time="2023-02-09T05:00:03+01:00" level=info msg="Removed tar file `/tmp/traefik-backup-2023-02-09T05-00-01.tar.gz`."
traefik-backuptest-backup-1  | time="2023-02-09T05:00:03+01:00" level=info msg="Finished running backup tasks."
```

**Screenshot of the support case**
![image](https://user-images.githubusercontent.com/11896495/217926949-dc00c01e-afdd-4442-a7d8-acbe32e7fe59.png)

**Permissions of the App Key**
```deleteFiles, listBuckets, listFiles, readBucketEncryption, readBucketReplications, readBuckets, readFiles, shareFiles, writeBucketEncryption, writeBucketReplications, writeFiles```
