### ISSUE TITLE
`archive-post` hook runs before archive?

### ISSUE THREAD

**Issue by dlford** [offen/docker-volume-backup#187]
**Describe the bug**
I would expect `archive-post` to run after archiving, but it seems to run before causing backup to fail.

**To Reproduce**
```yml
version: "2.2"
services:
  # ...
  kibana_rsync:
    container_name: elk_kibana_rsync
    tty: true
    image: eeacms/rsync
    restart: unless-stopped
    labels:
      - docker-volume-backup.exec-label=elk
      - docker-volume-backup.archive-pre=sh -c "rsync -aAX --ignore-missing-args --delete-missing-args /data/ /bu/"
      - docker-volume-backup.archive-post=sh -c "rm -rf /bu/*"
    volumes:
      - kibana:/data:ro
      - kibana_bu:/bu
  backup:
    container_name: elk_backup
    image: offen/docker-volume-backup:latest
    restart: unless-stopped
    environment:
      BACKUP_FILENAME: backup.tar.gz
      NOTIFICATION_URLS: "..."
      NOTIFICATION_LEVEL: error
      EXEC_LABEL: elk
      AWS_ENDPOINT: "..."
      AWS_S3_BUCKET_NAME: "..."
      AWS_ACCESS_KEY_ID: "..."
      AWS_SECRET_ACCESS_KEY: "..."
    volumes:
      - kibana_bu:/backup/kibana:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
volumes:
  kibana:
  kibana_bu:
```

**Expected behavior**
`archive-post` should run after tar archive is created.

**Version (please complete the following information):**
 - Image Version: latest (`sha256:837cbec53ba8fcaec3ad1f9d2a25086ad33fdbfa90585dc9f92e1947e1dea15d`)
 - Docker Version: 23.0.0
 - Docker Compose Version (if applicable): 23.0.0

**Additional context**

Here are the logs for the most recent run showing the `archive-pre` command executing, followed by `archive-post`, and then the archive step fails because the files are all gone.

```
time="2023-02-10T00:00:32-07:00" level=info msg="Running docker-volume-backup.archive-pre command sh -c \"rsync -aAX --ignore-missing-args --delete-missing-args /data/ /bu/\" for container elk_kibana_rsync"
time="2023-02-10T00:11:12-07:00" level=info msg="Running docker-volume-backup.archive-post command sh -c \"rm -rf /bu/*\" for container elk_kibana_rsync"
time="2023-02-10T00:11:12-07:00" level=error msg="Fatal error running backup: createArchive: error compressing backup folder: createArchive: error creating archive: compress: error writing /backup/kibana/chromium-26SeJH to archive: writeTarGz: error getting file infor for /backup/kibana/chromium-26SeJH: lstat /backup/kibana/chromium-26SeJH: no such file or directory"
time="2023-02-10T00:11:12-07:00" level=info msg="Removed tar file `/tmp/backup.tar.gz`."crond: crond (busybox 1.35.0) started, log level 8
````
