### ISSUE TITLE
Telegram Notifications not working

### ISSUE THREAD

**Issue by hugomickael** [offen/docker-volume-backup#194]
Hi, I'm using the following code to send a telegram notification but I'm not receiving it, and cannot see any error on the logs. The link is correct as I already tested it on another container.

```yml
backup:
    image: offen/docker-volume-backup:latest
    container_name: backup
    restart: unless-stopped
    environment:
      BACKUP_CRON_EXPRESSION: "0 4 * * 1"
      BACKUP_FILENAME: "volumes-backup-%Y-%m-%d.tar.gz"
      BACKUP_LATEST_SYMLINK: "volumes-backup-latest.tar.gz"
      BACKUP_RETENTION_DAYS: "30"    
      NOTIFICATION_URLS: "telegram://XXXXXXXXXXXXX:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx@telegram?chats=XXXXXXXXXXXXX&preview=No"
    volumes:
```
