### ISSUE TITLE
Preserving Last Backup of Each Year: Configuring Backup Retention

### ISSUE THREAD

**Issue by zN3utr4l** [offen/docker-volume-backup#196]
**What are you trying to do?**
I was wondering if it would be possible, through some configuration, to **prevent the deletion of the last backup of each year**.

For example, if it is **31st December 2022**, and I perform a backup, two days later, according to my configuration, the 31st backup will be deleted, is it possible to not delete it?

For instance, by moving each backup to its own folder, such as **backup/2022**, **backup/2023,** and every time you look for the backups to delete, deleting them in the **current year's folder**, or for each year the backups of _**BACKUP_RETENTION_DAYS**_ are deleted but starting from December 31st, that is, according to my configuration, **_BACKUP_RETENTION_DAYS=2_**, the backups of December 31st and December 30th **will remain in the system**.

**What is your current configuration?**
```
backup:
        image: offen/docker-volume-backup:v2.25.1
        logging:
            driver: "json-file"
            options:
                max-file: "6"
                max-size: 1024m
        user: root
        restart: always
        mem_limit: 256m
        mem_reservation: 100m
        container_name: backup
        environment:
            - BACKUP_SOURCES='/backup'
            - BACKUP_CRON_EXPRESSION='0 2-12/10 * * *'
            - BACKUP_FILENAME='backup-%Y-%m-%dT%H-%M-%S.tar.gz'
            - BACKUP_PRUNING_PREFIX='backup-'
            - BACKUP_RETENTION_DAYS=2
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - backup:/backup:ro
            - C:\BackupVolume:/archive
```
