### ISSUE TITLE
Backup of overseerr:latest data volume causes backup to fail

### ISSUE THREAD

**Issue by Fridgemagnet** [offen/docker-volume-backup#21]
Log entry for failed backup:
"level=fatal msg="Fatal error running backup: takeBackup: error compressing backup folder: archive/tar: write too long"

The overseerr container has the same config necessary to stop (before the backup) and start (afterwards) as every other container I have in my automated backup:

    labels:
      - docker-volume-backup.stop-during-backup=true
      
I unfortunately do not know if there are any other logs that I can have a look at to get more info.

The backup of the overseerr container's data volume had been working up until recently and suddenly didn't anymore after a recent update of the offen/docker-volume-backup image.

Thanks in advance for any help. :)

EDIT: Just a shot in the dark... might have to do with this commit: 70daa0308af26ca71422a78138f277d713cb3663

**Comment by m90** [comment]
> The backup of the overseerr container's data volume had been working up until recently and suddenly didn't anymore after a recent update of the offen/docker-volume-backup image

Do you run `latest`? In case yes, you might want to lock your version numbers (i.e. do not use `latest`) as it seems you have inadvertently upgraded to a new major version (which is a rewrite from scratch, thus v2). See: https://github.com/offen/docker-volume-backup/releases/tag/v2.0.0

As for the failure itself: how big is the file you are updating?

**Comment by m90** [comment]
This seems pretty close to what is happening: https://stackoverflow.com/a/40003617/797194

Does your backup contain symlinked files?

**Comment by Fridgemagnet** [comment]
Thanks for the speedy reply, @m90 

I think you might be onto something with the symlink as the overseerr container does create a symlink log file. That was the only thing that seemed "out of the ordinary" when inspecting the overseerr config bind mount.

Just for clarification: The backup to my own S3 service running on my truenas storage server works flawlessly when excluding the overseer data volume.
I absolutely love your image... it was such a delight to use as a backup solution after trying so many other solutions that were not up to the task.

**Comment by m90** [comment]
Could you share the exact image and volume config you are using for the failing service so I can try to reproduce the issue on my end? Fixing it might be a little tricky though as the problem arises inside of a dependency here https://github.com/walle/targz

For the time being I would advise you to lock the docker-volume-backup image to v1.8.3,. which seems to work correctly if I understand you correctly.

**Comment by Fridgemagnet** [comment]
Image version set to 'v1.8.3' and the backup (including overseerr) worked as expected.

Here is my portainer stack for overseerr:
```
---
version: "3"
services:
  overseerr:
    image: ghcr.io/linuxserver/overseerr
    container_name: overseerr
    environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/Berlin
    volumes:
        - /home/user/docker/overseerr/config:/config
    network_mode: bridge
    ports:
        - 5055:5055
    restart: unless-stopped
    labels:
      - docker-volume-backup.stop-during-backup=true
```

/home/user/docker/overseerr/config is mounted to /backup/overseerr:ro on the docker-volume-backup container.
