### ISSUE TITLE
runLabeledCommands: error from errgroup: runLabeledCommands: error executing command: exec: running command exited 1

### ISSUE THREAD

**Issue by zN3utr4l** [offen/docker-volume-backup#218]
**Describe the bug**
The problem seems to be only on the container marked as :rw, on the one with no tag it gives no error (if backuped alone)

**To Reproduce**
```
    timescaledb:
        image: my/timescaledb:v2.10.3-pg14
        logging:
            driver: "json-file"
            options:
                max-file: "6"
                max-size: 1024m
        user: postgres
        container_name: timescale
        environment:
            - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
            - POSTGRES_DB=$POSTGRES_DB
            - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
        hostname: host-timeScale
        restart: always
        mem_limit: 13312m
        mem_reservation: 1024m
        command: -c config_file=/etc/postgresql.conf
        networks:
            DefaultNet:
                ipv4_address: 172.20.0.5
        ports:
            - "5432:5432"
        volumes:
            - timescale_data:/var/lib/postgresql/data:rw
            - backup:/tmp/backup
        labels:
            - docker-volume-backup.archive-pre=cp -r /var/lib/postgresql/data /tmp/backup/timescale
            - docker-volume-backup.archive-post=rm -rf /tmp/backup/timescale

    backup:
        image: my/docker-volume-backup:v2.27.0
        logging:
            driver: "json-file"
            options:
                max-file: "6"
                max-size: 1024m
        user: root
        restart: always
        mem_limit: 256m
        mem_reservation: 100m
        container_name: backup
        environment:
            - BACKUP_SOURCES='/backup'
            - BACKUP_CRON_EXPRESSION='0 6,18 * * *'
            - BACKUP_FILENAME='backup-%Y-%m-%dT%H-%M-%S.tar.gz'
            - BACKUP_PRUNING_PREFIX='backup-'
            - BACKUP_RETENTION_DAYS=2
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - backup:/backup:ro
            - /home/backup-docker:/archive:rwd
        labels:
            - docker-volume-backup.prune-pre=sh /root/pruning.sh

    test:
        image: my/test:v1.0.0
        user: root
        volumes:
            - mongo_archive:/app/mongo
            - backup:/tmp/backup
        labels:
            - docker-volume-backup.archive-pre=cp -r /app/mongo /tmp/backup/mongo
            - docker-volume-backup.archive-post=rm -rf /tmp/backup/mongo
```

**Error**
```
docker exec backup backup
time="2023-05-26T07:32:28Z" level=info msg="Running docker-volume-backup.archive-pre command cp -r /app/mongo /tmp/backup/mongo for container test"
time="2023-05-26T07:32:28Z" level=info msg="Running docker-volume-backup.archive-pre command cp -r /var/lib/postgresql/data /tmp/backup/timescale for container timescale"
time="2023-05-26T07:32:28Z" level=error msg="Fatal error running backup: withLabeledCommands: archive: error running pre commands: runLabeledCommands: error from errgroup: runLabeledCommands: error executing command: exec: running command exited 1"
```

**Expected behavior**
Successfully Backup

**Version (please complete the following information):**
 - Image Version: 2.27.0
 - Docker Version: 20.10.21
 - Docker Compose Version (if applicable): 2.9.0
