### ISSUE TITLE
Clarity on how stop/restart container works ?

### ISSUE THREAD

**Issue by accforgithubtest** [offen/docker-volume-backup#283]
First, thank you for this neat project - I recently discovered offen and I have to say the documentation with specific examples categorized under the how-to and recipes is super helpful when it comes to easily finding info ! And you covered it working examples for some commonly used software ! Thank you.

**What are you trying to do?**
I am looking for some info / clarity on how stop/restart container works.
1. Is this understanding correct about the sequence of activities ?
    1. Stop all [multiple] containers under a given label, 
    2. Execute all the pre | post tasks across all containers
    3. Finish saving the archive
    4. Restart the containers using this label
    5. Other containers not using the label have not been stopped / restarted

2. Are there any other caveats I should be aware of / look into when trying to put multiple containers under a single label ?
 
3. For Pruning - Is there any builtin mechanism to check if the recent back-up files are good before deleting old one ? For e.g - Is there a way to get offen to check anything like -
    1. Check if the previous back up file is good to unzip
    2. Check / alert if there is a large / suspicious drop in the backup archive file size compare to the previous one ? Dont delete the larger older file in this case ?
I guess I am asking about some sort of safety mechanisms on if / how offen can check the newer archives before deleting the old ones.

**What is your current configuration?**
```
environment:
      # BACKUP_CRON_EXPRESSION: "0 3 * * *"
      BACKUP_FILENAME: backup-%Y-%m-%dT%H-%M-%S.tar.gz
      BACKUP_LATEST_SYMLINK: backup-latest.tar.gz
      BACKUP_PRUNING_PREFIX: backup-
      BACKUP_RETENTION_DAYS: 5
      BACKUP_STOP_CONTAINER_LABEL: schedule-1
```

**Log output**
I have currently removed running on schedule, and running it manually.
I was able to see the logs in the container logs (using portainer) when offen runs on a schedule. But I am unable to see any logs when running manually - Is this the expected behavior ? Is it possible to see the logs when running backup manually ?

Thanks !
