### ISSUE TITLE
"exec format error" at first start

### ISSUE THREAD

**Issue by shyonae** [offen/docker-volume-backup#306]
**What are you trying to do?**
Trying to get the container up and running.

**What is your current configuration?**
```
  ## DOCKER VOLUME BACKUP ##
  docker-volume-backup:
    image: offen/docker-volume-backup:latest
    container_name: docker-volume-backup
    user: 0:100 # needed to write to the nfs shared folder
    environment:
      <<: *environment
      BACKUP_CRON_EXPRESSION: "0 4 * * *"
      BACKUP_COMPRESSION: "gz"
      GZIP_PARALLELISM: 1
      BACKUP_FILENAME: backup-%Y-%m-%dT%H-%M-%S.tar.gz
      BACKUP_LATEST_SYMLINK: backup-latest.tar.gz
      BACKUP_SKIP_BACKENDS_FROM_PRUNE: s3,webdav,ssh,azure,dropbox
      BACKUP_ARCHIVE: "/archive"
      BACKUP_RETENTION_DAYS: "7"
      BACKUP_PRUNING_LEEWAY: "1m"
      BACKUP_PRUNING_PREFIX: "backup-"
      EXEC_FORWARD_OUTPUT: "true"
      EXEC_LABEL: "database"
    restart: always
    networks:
      - managementStackNetwork
      - socketProxyNetwork
    volumes:
      - ${DOCKERCONFDIR}/dozzle:/backup/dozzle:ro
      - /nfs/backups/docker-volumes-backups:/archive
```

**Log output**
`exec /root/entrypoint.sh: exec format error` + the container is restarting constantly

**Additional context**
I checked the image architecture and my VM's architecture, they're both amd64. What's the issue here? I'm running Ubuntu Server 22.04 LTS.

EDIT: edited the backup file name for a test, same error
