### ISSUE TITLE
"permission denied" when moving backup file?

### ISSUE THREAD

**Issue by shyonae** [offen/docker-volume-backup#307]
**What are you trying to do?**
 Run a backup with docker compose.

**What is your current configuration?**
```
## DOCKER VOLUME BACKUP ##
  docker-volume-backup:
    image: offen/docker-volume-backup:latest
    container_name: docker-volume-backup
    user: 0:100
    environment:
      DOCKER_HOST: tcp://dockerproxy:2375
      BACKUP_CRON_EXPRESSION: "55 19 * * *"
      BACKUP_COMPRESSION: "gz"
      GZIP_PARALLELISM: 1
      BACKUP_FILENAME: backup-%Y-%m-%dT%H-%M-%S.tar.gz
      BACKUP_LATEST_SYMLINK: backup-latest.tar.gz
      BACKUP_SKIP_BACKENDS_FROM_PRUNE: s3,webdav,ssh,azure,dropbox
      BACKUP_ARCHIVE: "/archive"
      BACKUP_RETENTION_DAYS: "7"
      BACKUP_PRUNING_LEEWAY: "1m"
      BACKUP_PRUNING_PREFIX: "backup-"
      EXEC_FORWARD_OUTPUT: "true"
      EXEC_LABEL: "database"
    restart: always
    networks:
      - managementStackNetwork
      - socketProxyNetwork
    volumes:
      - ${DOCKERCONFDIR}/uptime-kuma:/backup/uptime-kuma:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /nfs/backups/docker-volumes-backups:/archive
```

**Log output**
```
Installing cron.d entry with expression 02 20 * * *.
Starting cron in foreground.
crond: crond (busybox 1.36.1) started, log level 8
crond: USER root pid  11 cmd backup 2>&1
time=2023-11-25T20:02:00.763+01:00 level=INFO msg="Stopping 1 container(s) labeled `docker-volume-backup.stop-during-backup=true` out of 29 running container(s)."
time=2023-11-25T20:02:11.270+01:00 level=INFO msg="Created backup of `/backup` at `/tmp/backup-2023-11-25T20-02-00.tar.gz`."
time=2023-11-25T20:02:11.858+01:00 level=INFO msg="Restarted 1 container(s) and the matching service(s)."
time=2023-11-25T20:02:11.876+01:00 level=ERROR msg="Fatal error running backup: copyArchive: error copying archive: (*localStorage).Copy: Error copying file to archive: open /archive/backup-2023-11-25T20-02-00.tar.gz: permission denied"
time=2023-11-25T20:02:11.906+01:00 level=INFO msg="Removed tar file `/tmp/backup-2023-11-25T20-02-00.tar.gz`."
```

**Additional context**
If I run `docker exec docker-volume-backup backup`, it creates the file just fine. These are the logs: 
```
time=2023-11-25T20:03:21.018+01:00 level=INFO msg="Stopping 1 container(s) labeled `docker-volume-backup.stop-during-backup=true` out of 29 running container(s)."
time=2023-11-25T20:03:31.304+01:00 level=INFO msg="Created backup of `/backup` at `/tmp/backup-2023-11-25T20-03-20.tar.gz`."
time=2023-11-25T20:03:32.115+01:00 level=INFO msg="Restarted 1 container(s) and the matching service(s)."
time=2023-11-25T20:03:35.681+01:00 level=INFO msg="Stored copy of backup `/tmp/backup-2023-11-25T20-03-20.tar.gz` in `/archive`." storage=Local
time=2023-11-25T20:03:35.685+01:00 level=INFO msg="Created/Updated symlink `backup-latest.tar.gz` for latest backup." storage=Local
time=2023-11-25T20:03:35.693+01:00 level=INFO msg="None of 1 existing backups were pruned." storage=Local
time=2023-11-25T20:03:35.730+01:00 level=INFO msg="Removed tar file `/tmp/backup-2023-11-25T20-03-20.tar.gz`."
time=2023-11-25T20:03:35.730+01:00 level=INFO msg="Finished running backup tasks."
```

If I enter the container with `docker exec -it docker-volume-backup /bin/sh` and I move into /archive, I can see all my files and even touch new files, with no problem.

Why is it not working only while running directly from the compose?

**Comment by m90** [comment]
As already mentioned here: https://github.com/offen/docker-volume-backup/issues/306#issuecomment-1826274275 I surmise your `user` directive is what's causing this. Setting a `user` is not really supported by this image as it comes with way too many edge cases and problems (#270).

Assuming this is indeed the problem, this is what I'd do in your case is:
- Remove the `user` from your service
- Store your backup in an intermediate loaction
- In a `post-copy` command, copy the intermediate file to your desired location. A `post-copy` command _can_ be run using a different non-root user.

**Comment by shyonae** [comment]
Oh! I'll try to do that and report back, thanks a lot

**Comment by shyonae** [comment]
Okay so I tried but it isn't working:
```
  ## DOCKER VOLUME BACKUP ##
  docker-volume-backup:
    image: offen/docker-volume-backup:latest
    container_name: docker-volume-backup
    environment:
      DOCKER_HOST: tcp://dockerproxy:2375
      BACKUP_CRON_EXPRESSION: "46 13 * * *"
      BACKUP_COMPRESSION: "gz"
      GZIP_PARALLELISM: 1
      BACKUP_FILENAME: backup-%Y-%m-%dT%H-%M-%S.tar.gz
      BACKUP_LATEST_SYMLINK: backup-latest.tar.gz
      BACKUP_SKIP_BACKENDS_FROM_PRUNE: s3,webdav,ssh,azure,dropbox
      BACKUP_ARCHIVE: "/archive"
      BACKUP_RETENTION_DAYS: "7"
      BACKUP_PRUNING_LEEWAY: "1m"
      BACKUP_PRUNING_PREFIX: "backup-"
      EXEC_FORWARD_OUTPUT: "true"
      EXEC_LABEL: "database"
    restart: always
    labels:
      - docker-volume-backup.copy-post=adduser -S -D 0 -G users
      - docker-volume-backup.copy-post=/bin/sh -c 'mv /archive/backup-* /nfs_backups/'
    networks:
      - managementStackNetwork
      - socketProxyNetwork
    volumes:
      - ${DOCKERCONFDIR}:/backup:ro
      - ${DOCKERCONFDIR}/docker-volume-backup/archive:/archive:rw
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /nfs/backups/docker-volumes-backups:/nfs_backups:rw
```

These are the logs: 
```
crond: USER root pid  10 cmd backup 2>&1
time=2023-11-26T13:46:00.777+01:00 level=INFO msg="Stopping 21 container(s) labeled `docker-volume-backup.stop-during-backup=true` out of 28 running container(s)."
time=2023-11-26T13:48:54.394+01:00 level=INFO msg="Created backup of `/backup` at `/tmp/backup-2023-11-26T13-46-00.tar.gz`."
time=2023-11-26T13:49:15.071+01:00 level=INFO msg="Restarted 21 container(s) and the matching service(s)."
time=2023-11-26T13:50:19.412+01:00 level=INFO msg="Stored copy of backup `/tmp/backup-2023-11-26T13-46-00.tar.gz` in `/archive`." storage=Local
time=2023-11-26T13:50:19.481+01:00 level=INFO msg="Created/Updated symlink `backup-latest.tar.gz` for latest backup." storage=Local
time=2023-11-26T13:50:19.657+01:00 level=INFO msg="None of 1 existing backups were pruned." storage=Local
time=2023-11-26T13:50:19.988+01:00 level=INFO msg="Removed tar file `/tmp/backup-2023-11-26T13-46-00.tar.gz`."
time=2023-11-26T13:50:19.988+01:00 level=INFO msg="Finished running backup tasks."
```

I probably used the post label wrongly, right? What can I do to make it work?

**Comment by m90** [comment]
You can only define the label once, i.e. you will likely want to use:

```yaml
 - docker-volume-backup.copy-post=/bin/sh -c 'adduser -S -D 0 -G users && mv /archive/backup-* /nfs_backups/'

**Comment by shyonae** [comment]
I'll try and report back when I get the chance, thank you

**Comment by shyonae** [comment]
Nothing, didn't work, logs here:
```
time=2023-11-27T04:00:00.824+01:00 level=INFO msg="Stopping 21 container(s) labeled `docker-volume-backup.stop-during-backup=true` out of 30 running container(s)."
time=2023-11-27T04:03:41.000+01:00 level=INFO msg="Created backup of `/backup` at `/tmp/backup-2023-11-27T04-00-00.tar.gz`."
time=2023-11-27T04:04:00.315+01:00 level=INFO msg="Restarted 21 container(s) and the matching service(s)."
time=2023-11-27T04:06:33.075+01:00 level=INFO msg="Stored copy of backup `/tmp/backup-2023-11-27T04-00-00.tar.gz` in `/archive`." storage=Local
time=2023-11-27T04:06:33.134+01:00 level=INFO msg="Created/Updated symlink `backup-latest.tar.gz` for latest backup." storage=Local
time=2023-11-27T04:06:33.410+01:00 level=INFO msg="None of 2 existing backups were pruned." storage=Local
time=2023-11-27T04:06:33.899+01:00 level=INFO msg="Removed tar file `/tmp/backup-2023-11-27T04-00-00.tar.gz`."
time=2023-11-27T04:06:33.899+01:00 level=INFO msg="Finished running backup tasks."
```

And compose here:
```
...
 restart: always
    labels:
      - docker-volume-backup.copy-post=/bin/sh -c 'adduser -S -D 0 -G users && mv /archive/backup-* /nfs_backups/'
    networks:
      - managementStackNetwork
      - socketProxyNetwork
    volumes:
      - ${DOCKERCONFDIR}:/backup:ro
      - ${DOCKERCONFDIR}/docker-volume-backup/archive:/archive:rw
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /nfs/backups/docker-volumes-backups:/nfs_backups:rw
```
What could it be this time?
