### ISSUE TITLE
unexpected behaviour with docker socket proxy

### ISSUE THREAD

**Issue by pixxon** [offen/docker-volume-backup#342]
**Describe the bug**
Service downscaling seemingly hangs when proper rights are not set on the docker socket proxy.

**To Reproduce**
```yaml
...
services:
  target:
    ...
    deploy:
      labels:
        docker-volume-backup.stop-during-backup: sonarr

  minio_backup:
    image: offen/docker-volume-backup:v2.36.1
    environment:
      BACKUP_STOP_DURING_BACKUP_LABEL: anything
      DOCKER_HOST: tcp://docker_socket_proxy:2375
    ...
  docker_socket_proxy:
    image: tecnativa/docker-socket-proxy:0.1
    environment:
      CONTAINERS: 1
      SERVICES: 1
      ALLOW_START: 1
      ALLOW_STOP: 1
      INFO: 1
#      POST: 1
    ...
```
Forget adding `POST` permissions for the proxy.

**Expected behavior**
Script panics early due to lack of permissions. I believe we are stuck in this [wait](https://github.com/offen/docker-volume-backup/blob/main/cmd/backup/stop_restart.go#L223). I think if the scale down fails, we should not wait for it to complete. 

**Version (please complete the following information):**
 - Image Version: v2.36.1
 - Docker Version: 25.0.1, build 29cf629

**Additional context**
It would also be handy to provide a sample to the [docker-socket-proxy](https://offen.github.io/docker-volume-backup/how-tos/use-custom-docker-host.html) configuration with maybe comments on which permission is required for which setting. ( For example we early panic if `INFO` is not present. )
