### ISSUE TITLE
SSH-Backend Problems

### ISSUE THREAD

**Issue by INeido** [offen/docker-volume-backup#350]
**What are you trying to do?**
Use SSH as a backend.

**What is your current configuration?**
compose:
```
backup:
    container_name: co_backup
    image: offen/docker-volume-backup
    volumes:
      - /mnt/tank/docker/stacks/code:/etc/dockervolumebackup/conf.d
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /mnt/tank/docker/stacks/code/code:/backup/co_code:ro
    restart: unless-stopped
```
.env:
```
# Code
BACKUP_SOURCES="/backup/co_code"
BACKUP_FILENAME="code.tar.gz"
BACKUP_CRON_EXPRESSION="*/1 * * * *"
BACKUP_RETENTION_DAYS="30"
SSH_HOST_NAME="192.168.1.3"
SSH_PORT="13378"
SSH_USER="backup"
SSH_PASSWORD="CENSORED"
SSH_REMOTE_PATH="/volume1/backup/code"
```

**Log output**
```
time=2024-02-12T11:45:21.219-08:00 level=INFO msg="Successfully scheduled backup backup.env with expression */1 * * * *"

time=2024-02-12T11:46:00.036-08:00 level=INFO msg="Now running script on schedule */1 * * * *"

time=2024-02-12T11:46:00.166-08:00 level=ERROR msg="Unexpected error running schedule */1 * * * *: runScript: error instantiating script: newScript: error creating ssh storage backend: NewStorageBackend: error creating sftp client: ssh: subsystem request failed" error="runScript: error instantiating script: newScript: error creating ssh storage backend: NewStorageBackend: error creating sftp client: ssh: subsystem request failed"
```

**Additional context**
I can access the server through SSH using a terminal with the same login as provided above. The SSH-Server is a Synology NAS, if that matters at all.
Am I missing something, is this not how SSH was intended?

**Comment by m90** [comment]
I think you will still need to mount the key you want to use to authenticate.

See: https://offen.github.io/docker-volume-backup/recipes/#backing-up-to-ssh

and the test case for the `ssh` storage: https://github.com/offen/docker-volume-backup/blob/4c74313222e3a0f06b7aa87b672c703735babdb7/test/ssh/docker-compose.yml

**Comment by INeido** [comment]
I set up a keypair and got it working in principle (so using a terminal on another pc), but still get the same error:

```
time=2024-02-12T14:08:00.418-08:00 level=ERROR msg="Unexpected error running schedule */1 * * * *: runScript: error instantiating script: newScript: error creating ssh storage backend: NewStorageBackend: error creating sftp client: ssh: subsystem request failed" error="runScript: error instantiating script: newScript: error creating ssh storage backend: NewStorageBackend: error creating sftp client: ssh: subsystem request failed"
```

New config looks like this:
```
# Code
BACKUP_SOURCES="/backup/co_code"
BACKUP_FILENAME="code.tar.gz"
BACKUP_CRON_EXPRESSION="*/1 * * * *"
BACKUP_RETENTION_DAYS="30"
SSH_HOST_NAME="192.168.1.3"
SSH_PORT="13378"
SSH_USER="backup"
SSH_IDENTITY_PASSPHRASE="CENSORED"
SSH_REMOTE_PATH="/volume1/backup/code"
```

```
backup:
    container_name: co_backup
    image: offen/docker-volume-backup
    volumes:
      - /mnt/tank/docker/stacks/code:/etc/dockervolumebackup/conf.d
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /mnt/tank/docker/backup/id_rsa:/root/.ssh/id_rsa
      - /mnt/tank/docker/stacks/code/code:/backup/co_code:ro
    restart: unless-stopped
```
