### ISSUE TITLE
"Page not found" error when using with balena

### ISSUE THREAD

**Issue by mlxyz** [offen/docker-volume-backup#375]
**Describe the bug**
I am trying to use the container in a balena cloud environment.
This is the excerpt from the docker compose file:
```
  backup:
    image: offen/docker-volume-backup:latest
    restart: always
    volumes:
      - paperless_media:/backup/paperless-media:ro
      - paperless_data:/backup/paperless-data:ro
      - paperless_pgdata:/backup/paperless-pgdata:ro
      - caddy_data:/backup/caddy-data:ro
      - caddy_config:/backup/caddy-config:ro
    privileged: true
    labels:
      io.balena.features.balena-socket: "1"
    networks:
      - paperless
      - caddy
 ```

When running the backup, I get the following error message:
`time=2024-02-24T10:49:55.700Z level=ERROR msg="Fatal error running command: page not found" error="main.(*command).runAsCommand: error running script: main.runScript.func4: error running script: main.(*script).stopContainersAndServices: error querying for services: Error response from daemon: page not found"`

`DOCKER_HOST` is set:
```
~ # printenv | grep DOCKER
DOCKER_HOST=unix:///host/run/balena-engine.sock
```

**To Reproduce**
1. Setup balena cloud device with backup container and consuming container
2. Start backup

**Expected behavior**
Backup running without any issues.

**Version (please complete the following information):**
 - Image Version: v2.38.1
 - Docker Version: v20.10.43
 - Docker Compose Version (if applicable): 

**Additional context**
Balena-engine:
```
Client:
 Version:           v20.10.43
 API version:       1.41
 Go version:        go1.17.13
 Git commit:        0be8046a1c191ad789a65d7d8429d899d6bc9fbe
 Built:             Tue Feb  6 08:42:34 2024
 OS/Arch:           linux/arm64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          v20.10.43
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.13
  Git commit:       0be8046a1c191ad789a65d7d8429d899d6bc9fbe
  Built:            Tue Feb  6 08:42:34 2024
  OS/Arch:          linux/arm64
  Experimental:     true
 containerd:
  Version:          1.6.6+unknown
  GitCommit:        
 runc:
  Version:          unknown
  GitCommit:        
 balena-engine-init:
  Version:          0.13.0
  GitCommit:        949e6fa-dirty
```
