### ISSUE TITLE
Automated backups not running when using multiple retention schedules

### ISSUE THREAD

**Issue by rurickdev** [offen/docker-volume-backup#474]
**What are you trying to do?**

I'm trying to do backups automatically for day (3 days retention), week (1 month retention) and month (3 months retention)

**What is your current configuration?**

I basically follow the receipt from here https://offen.github.io/docker-volume-backup/how-tos/define-different-retention-schedules.html and here https://offen.github.io/docker-volume-backup/how-tos/run-multiple-schedules.html
with a couple for tweaks
```env
# 01daily.conf
BACKUP_FILENAME="daily-backup-%Y-%m-%dT%H-%M-%S.tar.gz"
BACKUP_CRON_EXPRESSION="0 2 * * *"
BACKUP_PRUNING_PREFIX="daily-backup-"
BACKUP_RETENTION_DAYS="3"


# 02weekly.conf
BACKUP_FILENAME="weekly-backup-%Y-%m-%dT%H-%M-%S.tar.gz"
BACKUP_CRON_EXPRESSION="0 3 * * 1"
BACKUP_PRUNING_PREFIX="weekly-backup-"
BACKUP_RETENTION_DAYS="31"


# 03monthly.conf
BACKUP_FILENAME="monthly-backup-%Y-%m-%dT%H-%M-%S.tar.gz"
BACKUP_CRON_EXPRESSION="0 4 1 * *"
BACKUP_PRUNING_PREFIX="monthly-backup-"
BACKUP_RETENTION_DAYS="93"
```

And my Docker compose looks like this
```yml
services:
  backup:
    image: offen/docker-volume-backup:v2
    container_name: backup
    volumes:
      - /${XDG_RUNTIME_DIR}/docker.sock:/var/run/docker.sock:ro
      - ${BACKUP_DIR}:/archive
      - ${VOLUME_DIR}/backup/conf.d:/etc/dockervolumebackup/conf.d
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    user: 0:0 # Running on rootless, if not set to 0:0 the write file fails due permissions
    restart: always
```

I use `compose.override` to add the desired mounts and tag the desired containers to stop, so I don't overpopulate this compose and this allows me to reuse the setup on other machines.

I confirmed that `backup` and my services are right tagged and drives mounted, and also trigger a first backup manually to ensure the config works.

**Log output**

This is the only logs the container gives me
```log
time=2024-09-21T02:48:12.387-06:00 level=INFO msg="Successfully scheduled backup 01daily.conf with expression 0 2 * * *"
time=2024-09-21T02:48:12.387-06:00 level=INFO msg="Successfully scheduled backup 02weekly.conf with expression 0 3 * * 1"
time=2024-09-21T02:48:12.387-06:00 level=INFO msg="Successfully scheduled backup 03monthly.conf with expression 0 4 1 * *"
time=2024-09-23T09:58:46.182-06:00 level=INFO msg="Successfully scheduled backup 01daily.conf with expression 0 2 * * *"
time=2024-09-23T09:58:46.193-06:00 level=INFO msg="Successfully scheduled backup 02weekly.conf with expression 0 3 * * 1"
time=2024-09-23T09:58:46.209-06:00 level=INFO msg="Successfully scheduled backup 03monthly.conf with expression 0 4 1 * *"
```

**Additional context**

Even when the log says the backup configs are schedule, the backups seems to not run, on the `/archive` directory there are no new backup files.

If I run the backups manually following this https://offen.github.io/docker-volume-backup/how-tos/manual-trigger.html for every one of my configuration the backups are created as expected on the `/archive` mounted volume, meaning that the configuration works but for some reason the cronjob is not trigger.
