### ISSUE TITLE
Local backup not cleaned up by retention policy

### ISSUE THREAD

**Issue by ChainsLunatic** [offen/docker-volume-backup#496]
**Describe the bug**
Using local backup `/archive` leaves me with backups that are not cleaned up by the configured retention policy. Dropbox on the other hand is being cleaned up correctly.

**To Reproduce**
1. Setup backup utilizing retention policy of 3 days

```yaml
image: offen/docker-volume-backup:latest
environment:
  DROPBOX_APP_KEY: "░░░░░░░░░░░░░░░"
  DROPBOX_APP_SECRET: "░░░░░░░░░░░░░░░"
  DROPBOX_REFRESH_TOKEN: "░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░"
  DROPBOX_REMOTE_PATH: "/Apps/░░░░░░░░░░░░░/backups"
  BACKUP_CRON_EXPRESSION: "0 2 * * *"
  BACKUP_RETENTION_DAYS: "3"
volumes:
  - /var/run/docker.sock:/var/run/docker.sock:ro
  - /etc/timezone:/etc/timezone:ro
  - /etc/localtime:/etc/localtime:ro

  - backup-data:/archive
```

3. Let it do it's jobs for e.g. a week
4. Collect directory content

```bash
~ # ls -la /archive
total 4327680
drwxr-xr-x    2 1000     1000             0 Nov 25 02:01 .
drwxr-xr-x    1 root     root          4096 Nov 17 13:11 ..
-rwxr-xr-x    1 1000     1000     551793735 Nov 19 02:01 backup-2024-11-19T02-00-00.tar.gz
-rwxr-xr-x    1 1000     1000     555052403 Nov 20 02:01 backup-2024-11-20T02-00-00.tar.gz
-rwxr-xr-x    1 1000     1000     558087120 Nov 21 02:01 backup-2024-11-21T02-00-00.tar.gz
-rwxr-xr-x    1 1000     1000     561238941 Nov 22 02:01 backup-2024-11-22T02-00-00.tar.gz
-rwxr-xr-x    1 1000     1000     562819809 Nov 23 02:01 backup-2024-11-23T02-00-00.tar.gz
-rwxr-xr-x    1 1000     1000     566158530 Nov 24 02:01 backup-2024-11-24T02-00-00.tar.gz
-rwxr-xr-x    1 1000     1000     568411176 Nov 25 02:01 backup-2024-11-25T02-00-00.tar.gz
```

**Expected behavior**
I would expect only 11/22 to 11/25 to be left after pruning.

**Version (please complete the following information):**
 - Image Version: `offen/docker-volume-backup            latest    4c971ebeada2   3 months ago   34.3MB`
 - Docker Version: 27.3.1
 - Docker Compose Version (if applicable): v2.29.7

**Additional context**
