### ISSUE TITLE
Backblaze returns 408

### ISSUE THREAD

**Issue by DaruZero** [offen/docker-volume-backup#505]
**What are you trying to do?**
Store backups on a Backblaze B2 bucket

**What is your current configuration?**
`compose.yaml`:
```yaml
services:
  backup:
    image: offen/docker-volume-backup:latest
    restart: unless-stopped
    env_file: ./backup.env
    volumes:
      # Volumes to backup
      - #redacted
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./local_backups:/archive
      - ./template:/etc/dockervolumebackup/notifications.d/01.template
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

volumes:
  # redacted
```

`backup.env`:
```bash
GZIP_PARALLELISM=0
BACKUP_FILENAME="backup-docker-%Y-%m-%dT%H-%M-%S.{{ .Extension }}"
BACKUP_FILENAME_EXPAND="true"
AWS_S3_BUCKET_NAME=redacted
AWS_ACCESS_KEY_ID=redacted
AWS_SECRET_ACCESS_KEY=redacted
AWS_ENDPOINT="s3.eu-central-003.backblazeb2.com"
BACKUP_ARCHIVE="/archive"
BACKUP_RETENTION_DAYS="7"
BACKUP_PRUNING_LEEWAY="2m"
NOTIFICATION_URLS=redacted
NOTIFICATION_LEVEL="error"
```

**Log output**
```text
backup-1  | time=2024-12-10T22:39:50.424+01:00 level=INFO msg="Successfully scheduled backup from environment with expression @daily"
backup-1  | time=2024-12-11T00:00:00.073+01:00 level=INFO msg="Now running script on schedule @daily"
backup-1  | time=2024-12-11T00:00:03.769+01:00 level=INFO msg="Created backup of `/backup` at `/tmp/backup-docker-2024-12-11T00-00-00.tar.gz`."
backup-1  | time=2024-12-11T00:00:04.148+01:00 level=INFO msg="Stored copy of backup `/tmp/backup-docker-2024-12-11T00-00-00.tar.gz` in `/archive`." storage=Local
backup-1  | time=2024-12-11T00:01:09.366+01:00 level=INFO msg="Removed tar file `/tmp/backup-docker-2024-12-11T00-00-00.tar.gz`."
backup-1  | time=2024-12-11T00:01:09.764+01:00 level=ERROR msg="Unexpected error running schedule @daily: s3.(*s3Storage).Copy: error uploading backup to remote storage: [Message]: '408 ', [Code]: 408 , [StatusCode]: 408" error="main.runScript.func4: error running script: main.(*script).copyArchive: error copying archive: s3.(*s3Storage).Copy: error uploading backup to remote storage: [Message]: '408 ', [Code]: 408 , [StatusCode]: 408"
```

**Additional context**
Since the first of december I started getting this `408` response from Backblaze. I haven't changed anything in either the docker configuration or the B2 bucket. I know that probably is not a problem related with docker-volume-backup, but I am not sure where to start. I have other services on different machines (like restic) that are still working. Digging a bit on the internet, it seems that the `408` code should be a response for the B2 CLI, not for the S3-compatible APIs.
Any idea about anything that I should do to fix this?
