### ISSUE TITLE
Variable expansion works in Compose but not Swarm

### ISSUE THREAD

**Issue by dlmw** [offen/docker-volume-backup#515]
**Describe the bug**
I tried variable expansion with Docker Compose and it worked fine. However, running the same Compose file via `docker stack deploy -c` gave me the error `failed to create service freshrss_backup: Error response from daemon: rpc error: code = InvalidArgument desc = expanding env failed: expanding env "BACKUP_FILENAME=\"$BACKUP_NAME-%!Y(MISSING)-%!m(MISSING)-%!d(MISSING)T%!H(MISSING)-%!M(MISSING)-%!S(MISSING).{{ .Extension }}\"": template: expansion:1:35: executing "expansion" at <.Extension>: can't evaluate field Extension in type *template.Context`

**To Reproduce**
```
// backup.env
BACKUP_CRON_EXPRESSION="40 * * * *"
BACKUP_FILENAME="$$BACKUP_NAME-%Y-%m-%dT%H-%M-%S.{{ .Extension }}"
BACKUP_FILENAME_EXPAND="true"
```

```yml
# docker-compose.yml
# note that you might need to change the networks and secrets to make it run
services:
  freshrss:
    image: freshrss/freshrss:1.25.0-alpine
    depends_on:
      - freshrss-db
    volumes:
      - freshrss-data:/var/www/FreshRSS/data
      - freshrss-extensions:/var/www/FreshRSS/extensions
    environment:
      CRON_MIN: '*/20'
      TZ: Europe/Paris
    networks:
      - reverse-proxy-network
      - freshrss-network

  freshrss-db:
    image: postgres:16.4-alpine
    volumes:
      - freshrss-db:/var/lib/postgresql/data
    secrets:
      - freshrss_db_password
    environment:
      POSTGRES_USER: freshrss
      POSTGRES_PASSWORD_FILE: /run/secrets/freshrss_db_password
      POSTGRES_DB: freshrss
    networks:
      - freshrss-network

  backup:
    image: offen/docker-volume-backup:v2.43.0
    env_file: ../backup.env
    environment:
      BACKUP_NAME: "gitea"
    volumes:
      - freshrss-data:/backup/freshrss-data:ro
      - freshrss-extensions:/backup/freshrss-extensions:ro
      - freshrss-db:/backup/freshrss-db:ro

volumes:
  freshrss-db:
  freshrss-data:
  freshrss-extensions:

secrets:
  freshrss_db_password:
    external: true

networks:
  reverse-proxy-network:
    external: true
  freshrss-network:
```

**Expected behavior**
It should work as it did in Docker Compose during tests.

**Version (please complete the following information):**
 - Image Version: v2.43.0
 - Docker Version: 25.0.6-ce

**Additional context**
