### ISSUE TITLE
Backups are sometimes 0 bytes, with no error notifications. The configuration seems fine to me.

### ISSUE THREAD

**Issue by gremo** [offen/docker-volume-backup#521]
On one of my servers, the application doesn't seem to work correctly. From time to time, backups result in 0-byte invalid archives.  I didn't received any notification email for errors. Running the `backup` command manually from inside the container results in "killed" sometimes with no other information (but most of the time it works and creates non-0-bytes archive).

![FTP](https://github.com/user-attachments/assets/64ac0751-829b-42c6-ad98-046f986b9bc5)

Backups are scheduled at 2 AM with a 30-day retention period. 

![dvb](https://github.com/user-attachments/assets/8c6f0ffa-eeb4-47a4-b0a9-c7aefd857dc0)

I've double-checked, and the mount points are set, so there is definitely "something to back up":

![mounts](https://github.com/user-attachments/assets/4e06b5ab-5202-4d84-8112-47c71893a687)

Here is the container log (that says nothing strange):

```txt
time=2025-01-08T11:54:24.186+01:00 level=INFO msg="Successfully scheduled backup from environment with expression 0 2 * * *"
time=2025-01-09T02:00:00.117+01:00 level=INFO msg="Now running script on schedule 0 2 * * *"
time=2025-01-09T02:00:01.697+01:00 level=INFO msg="Created backup of `/backup` at `/tmp/backup-2025-01-09T02-00-00.tar.gz`."
time=2025-01-09T02:00:05.458+01:00 level=INFO msg="Successfully scheduled backup from environment with expression 0 2 * * *"
time=2025-01-10T02:00:00.116+01:00 level=INFO msg="Now running script on schedule 0 2 * * *"
time=2025-01-10T02:00:01.046+01:00 level=INFO msg="Created backup of `/backup` at `/tmp/backup-2025-01-10T02-00-00.tar.gz`."
time=2025-01-10T02:00:04.186+01:00 level=INFO msg="Successfully scheduled backup from environment with expression 0 2 * * *"
```

**EDIT**: two of the 0-bytes backup are still in the container `/tmp` directory, so what happened?

```shell
~ # ls -la /tmp/
total 65388
drwxrwxrwt    1 root     root          4096 Jan 10 13:50 .
drwxr-xr-x    1 root     root          4096 Jan  8 11:54 ..
-rw-r--r--    1 root     root      32749973 Jan  9 02:00 backup-2025-01-09T02-00-00.tar.gz
-rw-r--r--    1 root     root      34184201 Jan 10 02:00 backup-2025-01-10T02-00-00.tar.gz
```

**Comment by m90** [comment]
My hunch is that in these cases, your container runtime terminates your backup service before it's able to complete. Hence, there are also no failure notifications as it won't even get that far in the procedure before being killed.

Do you have any resource limits set on the service? Are you dealing with rather large archive files that could theoretically max out the available disk space?

**Comment by gremo** [comment]
> Do you have any resource limits set on the service?

Not at all.

> Are you dealing with rather large archive files that could theoretically max out the available disk space?

Backup size actually is like 30MB. I don't have space related issues:

```txt
Filesystem      Size  Used Avail Use% Mounted on
devtmpfs        4.0M     0  4.0M   0% /dev
tmpfs           1.8G     0  1.8G   0% /dev/shm
tmpfs           713M   68M  645M  10% /run
/dev/sda1        38G  7.9G   28G  22% /
/dev/sda14       64M  7.1M   57M  12% /boot/efi
```

Could the failed removal of archives in the container's `/tmp` folder be the reason?

**Comment by m90** [comment]
> Could the failed removal of archives in the container's /tmp folder be the reason?

Not really. Rather, this is another hint that someone from the outside is terminating the process, which means it's unable to perform clean up tasks. Just like notifications, cleanup tasks would still happen if you have a failing backup, but that failure is handled at application level. Instead, something must be force restarting your container while it's doing a backup run.

However, it's strange this is happening without resource limits set, but maybe the entire host is out of capacity? It'd be interesting to `docker inspect` such a backup container and look if, why and how often it's being restarted.

**Comment by gremo** [comment]
Tonight backup is also 0 bytes 😢 

> but maybe the entire host is out of capacity?

I don't think it's out of capacity. It's a small VPS yes, but it seems no such busy around 2 AM:

![Graph](https://github.com/user-attachments/assets/a89586e2-6dd8-49a0-ab13-147763452a44)

I've checked the restart count:

```bash
[root@myserver ~]# docker inspect e66bc8559b45 --format='{{.RestartCount}}'
3
```

```bash
[root@myserver ~]# docker inspect e66bc8559b45 --format='{{json .HostConfig.RestartPolicy}}'
{"Name":"unless-stopped","MaximumRetryCount":0}
```

```bash
[root@myserver ~]# docker inspect e66bc8559b45 --format='{{json .State}}'
{"Status":"running","Running":true,"Paused":false,"Restarting":false,"OOMKilled":false,"Dead":false,"Pid":1910866,"ExitCode":0,"Error":"","StartedAt":"2025-01-11T01:00:04.249114906Z","FinishedAt":"2025-01-11T01:00:04.033822318Z"
```

Here is some information that could help, but I'm not able to interpret it:

```bash
[root@myserver ~]# journalctl -u docker | grep -i e66bc8559b45
Jan 11 02:00:03 myserver.it dockerd[726]: time="2025-01-11T01:00:03.889544544Z" level=warning msg="failed to delete process" container=e66bc8559b456514cb0e6bd9b6ce1bad586d52af5fa328d088a5f64db5852d7c error="NotFound: container not created: not found" process=c900d3f3b4a3f6fd24b7a0311fb3f5c218290fea8f913f2a2678a90918a4528d
Jan 11 02:00:03 myserver.it dockerd[726]: time="2025-01-11T01:00:03.889656257Z" level=warning msg="failed to delete process" container=e66bc8559b456514cb0e6bd9b6ce1bad586d52af5fa328d088a5f64db5852d7c error="NotFound: container not created: not found" process=5c93ac063b91005b5a78a6e21281f1610d73964b48aa7bf59ecea38b2f8660d9
Jan 11 02:00:03 myserver.it dockerd[726]: time="2025-01-11T01:00:03.889794422Z" level=warning msg="failed to delete process" container=e66bc8559b456514cb0e6bd9b6ce1bad586d52af5fa328d088a5f64db5852d7c error="NotFound: container not created: not found" process=efec07b072bf44943803ba887ff0212490d486aff412c892d7bf7c3c8ff831a8
Jan 11 02:00:03 myserver.it dockerd[726]: time="2025-01-11T01:00:03.889848793Z" level=warning msg="failed to delete process" container=e66bc8559b456514cb0e6bd9b6ce1bad586d52af5fa328d088a5f64db5852d7c error="NotFound: container not created: not found" process=324dde5610e8efbf74da1ab94d7cc8a217ed96449b8bc39242cf85ff6342aa3d
Jan 11 02:00:03 myserver.it dockerd[726]: time="2025-01-11T01:00:03.889925292Z" level=warning msg="failed to delete process" container=e66bc8559b456514cb0e6bd9b6ce1bad586d52af5fa328d088a5f64db5852d7c error="NotFound: container not created: not found" process=84f125beb1fa3614cd080834d09fb2643ebfb3fcae628ef358bdcb61aa1484f4
Jan 11 02:00:03 myserver.it dockerd[726]: time="2025-01-11T01:00:03.890076400Z" level=info msg="ignoring event" container=e66bc8559b456514cb0e6bd9b6ce1bad586d52af5fa328d088a5f64db5852d7c module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
```

**Comment by m90** [comment]
Very hard to tell. It definitely looks like someone is terminating and restarting the container while it should be finishing the backup, but I also have no clue who is doing this and why?

Are you stopping containers during backup by labelling them? Are you maybe telling the backup container to stop itself during backup? Then again this should give us consistent behavior for each run.

I'm a bit out of ideas here, maybe it'd be worth doing things like updating Docker and such as well.

**Comment by gremo** [comment]
> I'm a bit out of ideas here

Sure, no problem at all! In the meantime, thank you for your help, I'm very grateful.

> Are you stopping containers during backup by labelling them?

Yes but I think I've labelling them correctly. I have many Compose project, each with its own docker-volume-backup container, i.e:

```yaml
# Example compose.yaml for a given project
services:
    db:
        container_name: ${COMPOSE_PROJECT_NAME}-db
        image: mariadb:${MARIADB_TAG:?}
        environment:
            MARIADB_DATABASE: bookstack
            MARIADB_USER: bookstack
            MARIADB_PASSWORD: ${DB_PASSWORD?:}
            MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:?}
            TZ: ${TZ:?}
        volumes:
            - db-data:/var/lib/mysql
        networks:
            default:
                aliases:
                  - db.local
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
            start_period: 10s
            interval: 10s
            timeout: 5s
            retries: 3
        labels:
            - "docker-volume-backup.stop-during-backup=${COMPOSE_PROJECT_NAME}"

    dvb:
        container_name: ${COMPOSE_PROJECT_NAME}-dvb
        image: offen/docker-volume-backup
        environment:
            BACKUP_CRON_EXPRESSION: ${BACKUP_FREQUENCY:-}
            BACKUP_RETENTION_DAYS: 7
            BACKUP_FILENAME: ${COMPOSE_PROJECT_NAME}-%Y-%m-%dT%H-%M-%S.{{ .Extension }}
            BACKUP_PRUNING_PREFIX: ${COMPOSE_PROJECT_NAME}-
            BACKUP_STOP_DURING_BACKUP_LABEL: ${COMPOSE_PROJECT_NAME}
        volumes:
            - bookstack-data:/backup/bookstack-data:ro
            - db-data:/backup/db-data:ro
            - ${BACKUP_ROOT:?}:/archive
            - /var/run/docker.sock:/var/run/docker.sock:ro
        restart: unless-stopped

```

`BACKUP_ROOT` is always `/srv/docker/backup` and frequency `@daily`. No problems at all, backup are always created correctly and rotated just fine.

The issue I'm having it's related to my "global" docker-volume-backup container which will copy  `/srv/docker/backup` to my SSH server, along with other VPS files.

Do you want to know the strangest thing? I have another VPS with the same structure and I have no such problem 😨
