### ISSUE TITLE
SSH: error creating sftp client: ssh: subsystem request failed"

### ISSUE THREAD

**Issue by Jasper51297** [offen/docker-volume-backup#525]
**What are you trying to do?**
I'm trying to use docker-volume-backup to write backups via SSH to my Synology NAS.

**What is your current configuration?**
I've enabled SSH key authentication on my NAS, and am able to connect using the key from the server running docker-volume-backup. I have also executed a cat command inside the container; the private key is readable/accessible.

My docker compose file:
```
 backup:
    image: offen/docker-volume-backup:latest
    restart: always
    env_file:  $DOCKERDIR/appdata/backup/backup.env
    volumes:
      - $DOCKERDIR:/backup:ro
      - $DOCKERDIR/id_ed_nas:/root/.ssh/id_rsa
      - /var/run/docker.sock:/var/run/docker.sock`
```

My environment variables:
BACKUP_COMPRESSION:	gz
BACKUP_CRON_EXPRESSION:	0 3 * * 0
BACKUP_FILENAME:	backup-%Y-%m-%dT%H-%M-%S.tar.gz
BACKUP_RETENTION_DAYS:	30
GZIP_PARALLELISM:	1
PATH:	/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
SSH_HOST_NAME:	192.168.50.200
SSH_IDENTITY_FILE:	/root/.ssh/id_rsa
SSH_PORT:	22
SSH_REMOTE_PATH:	/volume1/homes/Jasper/backups
SSH_USER:	jasper

**Log output**
```
$ docker exec docker-backup-1 backup
time=2025-01-21T08:06:11.423Z level=ERROR msg="Fatal error running command: ssh: subsystem request failed" error="main.(*command).runAsCommand: error running script: main.runScript: error instantiating script: main.(*script).init: error creating ssh storage backend: ssh.NewStorageBackend: error creating sftp client: ssh: subsystem request failed"
```

Any ideas what I'm doing wrong?
