### ISSUE TITLE
Backup archives are saved in /root/backups instead of the configured /archive path

### ISSUE THREAD

**Issue by VBE-Dickson** [offen/docker-volume-backup#540]
#### **What are you trying to do?**  
I am trying to configure `docker-volume-backup` to store backups on an external USB drive mounted at `/mnt/bigdur/immich_backups`. However, despite mounting the directory correctly, backups are always stored in `/root/backups` inside the container instead of `/archive`.  

#### **What is your current configuration?**  
```yaml
  backup:
    image: offen/docker-volume-backup:v2
    environment:
      BACKUP_CRON_EXPRESSION: "0 3 * * *"  # Sauvegarde quotidienne à 3h du matin
      BACKUP_FILENAME: "backup-%Y-%m-%dT%H-%M-%S.tar.gz"
      BACKUP_RETENTION_DAYS: 1
    volumes:
      - ${UPLOAD_LOCATION}:/backup/immich-upload:ro
      - ${DB_DATA_LOCATION}:/backup/immich-db:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/bigdur/immich_backups:/archive #ignored ???
    restart: always
```

#### **Log output**  
(When running the container, backups appear in `/root/backups` instead of `/archive`.)  
```bash
vincent@rpi5:~/immich-app $ docker exec 0dc29699ba84 backup
time=2025-02-23T18:35:34.385Z level=INFO msg="Stopping 1 out of 5 running container(s) as they were labeled docker-volume-backup.stop-during-backup=true."
time=2025-02-23T18:45:48.907Z level=INFO msg="Created backup of `/backup` at `/tmp/backup-2025-02-23T18-35-34.tar.gz`."
time=2025-02-23T18:45:49.131Z level=INFO msg="Restarted 1 container(s)."
time=2025-02-23T18:55:34.467Z level=INFO msg="Stored copy of backup `/tmp/backup-2025-02-23T18-35-34.tar.gz` in `/archive`." storage=Local
time=2025-02-23T18:55:34.468Z level=INFO msg="None of 1 existing backups were pruned." storage=Local
time=2025-02-23T18:55:34.772Z level=INFO msg="Removed tar file `/tmp/backup-2025-02-23T18-35-34.tar.gz`."
```

```bash
root@rpi5:~/backups# pwd
/root/backups
root@rpi5:~/backups# ls -lah
total 119G
drwxr-xr-x 2 root root 4.0K Feb 23 19:45 .
drwx------ 5 root root 4.0K Feb 23 16:01 ..
-rw-r--r-- 1 root root 119G Feb 23 19:55 backup-2025-02-23T18-35-34.tar.gz
``` 

```bash
root@rpi5:/mnt/bigdur# ls -lah
total 24K
drwxr-xr-x 3 root root 4.0K Feb 23 19:31 .
drwxr-xr-x 3 root root 4.0K Feb 23 15:49 ..
drwx------ 2 root root  16K Feb 23 15:40 lost+found 
```
(ignore lost+found thing, i dont really know what is this)

Is there an internal default override forcing backups to `/root/backups`? Do I need additional permissions for `/mnt/bigdur/immich_backups`? Any help would be appreciated. Thanks! 🙏
