### ISSUE TITLE
Unable to use Cloudflare r2 for backups

### ISSUE THREAD

**Issue by AlenGeoAlex** [offen/docker-volume-backup#564]
**Describe the bug**
Unable to backup to cloudflare r2 storage service 

![Image](https://github.com/user-attachments/assets/d55b6509-6355-431b-a9bc-8889e9ddf493)

```
time=2025-03-31T06:58:23.130Z level=INFO msg="Created backup of `/backup` at `/tmp/backup-2025-03-31T06-58-23.tar.zst`."
time=2025-03-31T06:58:23.302Z level=INFO msg="Removed tar file `/tmp/backup-2025-03-31T06-58-23.tar.zst`."
time=2025-03-31T06:58:23.302Z level=ERROR msg="Fatal error running command: s3.(*s3Storage).Copy: error uploading backup to remote storage: [Message]: '<html>\r\n<head><title>301 Moved Permanently</title></head>\r\n<body>\r\n<center><h1>301 Moved Permanently</h1></center>\r\n<hr><center>cloudflare</center>\r\n</body>\r\n</html>', [Code]: 301 Moved Permanently, [StatusCode]: 301" error="main.(*command).runAsCommand: error running script: main.runScript.func4: error running script: main.(*script).copyArchive: error copying archive: s3.(*s3Storage).Copy: error uploading backup to remote storage: [Message]: '<html>\r\n<head><title>301 Moved Permanently</title></head>\r\n<body>\r\n<center><h1>301 Moved Permanently</h1></center>\r\n<hr><center>cloudflare</center>\r\n</body>\r\n</html>', [Code]: 301 Moved Permanently, [StatusCode]: 301"
```

**To Reproduce**
Example Docker compose file:
```YAML
services:
  serviceY:

  serviceX:

  serviceX_backup:
    image: offen/docker-volume-backup:latest
    container_name: ServiceX_backup
    restart: unless-stopped
    environment:
      - AWS_ACCESS_KEY_ID=redacted
      - AWS_SECRET_ACCESS_KEY=redacted
      - AWS_ENDPOINT=redacted.r2.cloudflarestorage.com
      - BACKUP_COMPRESSION=zst
      - BACKUP_NAME=x
      - AWS_S3_BUCKET_NAME=x-backup
      - AWS_ENDPOINT_PROTO="https"
      - BACKUP_ARCHIVE="/archive"
      - BACKUP_RETENTION_DAYS=30
    volumes:
      - /opt/db/data:/backup:ro
      - /archive/db:/archive
```

**Expected behavior**
Successful upload of the backup file 

**Version (please complete the following information):**
 - Image Version: latest
 - Docker Version: Docker version 28.0.4, build b8034c0

I am not sure whether its due to some misconfiguration or something from the s3 client itself or even from Cloudflare itself.

Thanks and Regards

**Comment by m90** [comment]
I would Interpret the 301 error in a way that the endpoint you provide is not correct and r2 therefore tries to redirect the client somewhere else instead. Can you double check the value you put there?

**Comment by m90** [comment]
Maybe the bucket configuration is different in this case? I don't think there's anything I can do here as Cloudflare is being called, but responds 301, which is not expected. So either your endpoint is incorrect, or your bucket is configured differently.

**Comment by AlenGeoAlex** [comment]
Thanks again, but I think its something else, I tried the same bucket and same configuration on a different docker backup image solution [eeshugerman/postgres-backup](https://github.com/eeshugerman/postgres-backup-s3) and the same endpoint and config is fine there...

For now I will look for something else or spin up an image myself

Thanks and regards.

**Comment by framebassman** [comment]
btw it works with the following compose:
```yaml
  backup:
    image: offen/docker-volume-backup:v2.48.0
    restart: always
    environment:
      AWS_ACCESS_KEY_ID: ${CLOUDFLARE_R2_API_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${CLOUDFLARE_R2_API_ACCESS_SECRET}
      AWS_S3_BUCKET_NAME: backups
      AWS_ENDPOINT: ${CLOUDFLARE_R2_ENDPOINT}
      AWS_ENDPOINT_PROTO: https
      BACKUP_COMPRESSION: zst
      BACKUP_NAME: x
      BACKUP_RETENTION_DAYS: 30
```
