### ISSUE TITLE
WebDAV Backup returns first path segment in URL cannot contain colon

### ISSUE THREAD

**Issue by Ebnater** [offen/docker-volume-backup#578]
**What are you trying to do?**

I'm trying to move my Backup to my NAS using WebDAV. It is set up properly and i can access it without any problems from my Windows Device. I followed the Configuration Reference.

**What is your current configuration?**

```backup:
    image: offen/docker-volume-backup:v2.43.2
    environment:
      - BACKUP_STOP_DURING_BACKUP_LABEL=gitea
      - BACKUP_FILENAME=gitea-backup-%Y%m%d-%H%M%S.tar.gz
      - BACKUP_PRUNING_PREFIX=gitea-backup-
      - BACKUP_RETENTION_DAYS=14
      - WEBDAV_URL="https://webdav.example.com"
      - WEBDAV_USERNAME="vpsuser"
      - WEBDAV_PASSWORD="xx"
      - WEBDAV_PATH="vps_backup/"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - gitea:/backup/:ro
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: "host"
    depends_on:
      - server
    restart: always`
```

**Log output**

time=2025-04-23T09:41:03.855Z level=INFO msg="Stopping 1 out of 35 running container(s) as they were labeled docker-volume-backup.stop-during-backup=gitea."
time=2025-04-23T09:41:26.670Z level=INFO msg="Created backup of `/backup` at `/tmp/gitea-backup-20250423-094103.tar.gz`."
time=2025-04-23T09:41:26.883Z level=INFO msg="Restarted 1 container(s)."
time=2025-04-23T09:41:46.439Z level=INFO msg="Stored copy of backup `/tmp/gitea-backup-20250423-094103.tar.gz` in `/archive`." storage=Local
time=2025-04-23T09:41:46.635Z level=INFO msg="Removed tar file `/tmp/gitea-backup-20250423-094103.tar.gz`."
time=2025-04-23T09:41:46.635Z level=ERROR msg="Fatal error running command: first path segment in URL cannot contain colon" error="main.(*command).runAsCommand: error running script: main.runScript.func4: error running script: main.(*script).copyArchive: error copying archive: webdav.(*webDavStorage).Copy: error creating directory '\"/volume1/vps_backup\"' on server: parse \"%22https://webdav.example.com%22/%22/volume1/vps_backup%22/\": first path segment in URL cannot contain colon"

**Comment by m90** [comment]
The error is a bit cryptic to me as well, but my guess would be that you are passing quoted environment variables to the container (i.e. compare BACKUP_STOP_DURING_BACKUP_LABEL and WEBDAV_URL). Can you try using hash notation instead (which seems to be way less brittle):

```
environment:
  BACKUP_STOP_DURING_BACKUP_LABEL: gitea
  BACKUP_FILENAME: gitea-backup-%Y%m%d-%H%M%S.tar.gz
  BACKUP_PRUNING_PREFIX: gitea-backup-
  BACKUP_RETENTION_DAYS: 14
  WEBDAV_URL: "https://webdav.example.com"
  WEBDAV_USERNAME: "vpsuser"
  WEBDAV_PASSWORD: "xx"
  WEBDAV_PATH: "vps_backup/"
```

Your configuration itself looks correct.
