### ISSUE TITLE
AWS credentials are not loaded from files

### ISSUE THREAD

**Issue by MintyRoma** [offen/docker-volume-backup#581]
**What are you trying to do?**
I'm trying to set up a backup to S3-compatible storage using Docker Compose secrets to securely pass access keys. However, when the container attempts to upload the archive to the S3 storage, it fails with the following error:
```
time=2025-05-04T22:26:00.095Z level=ERROR msg="Unexpected error running schedule */1 * * * *: net/http: invalid header field value for \"Authorization\"" error="main.runScript.func4: error running script: main.(*script).copyArchive: error copying archive: s3.(*s3Storage).Copy: error uploading backup to remote storage: Get \"https://storage.example.com/bucketname/?location=\": net/http: invalid header field value for \"Authorization\""
```
If I use plain environment variables (instead of _FILE), everything works as expected.
I also verified that the secret files exist inside the container and their contents are correct.

**What is your current configuration?**
```
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    ...
    volumes:
      - config:/app/config # Make sure your local config directory exists

  oauthproxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    ...
    volumes:
      - proxy_config:/config

  srk:
    image: offen/docker-volume-backup
    restart: always
    volumes:
      - config:/backup/homepage:ro
      - proxy_config:/backup/proxy:ro
      #- /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      AWS_S3_PATH: "homepage-app"
      AWS_ENDPOINT: "storage.example.com"
      AWS_S3_BUCKET_NAME: "bucketname"
      #AWS_ACCESS_KEY_ID: ACCESSKEYID
      #AWS_SECRET_ACCESS_KEY: ACCESSKEYSECRET
      AWS_ACCESS_KEY_ID_FILE: "/run/secrets/yc_id"
      AWS_SECRET_ACCESS_KEY_FILE: "/run/secrets/yc_key"
      BACKUP_CRON_EXPRESSION: "*/1 * * * *"
      BACKUP_FILENAME: test-backup-%Y-%m-%dT%H-%M-%S.tar.gz
      BACKUP_RETENTION_DAYS: 30
    secrets:
      - yc_id
      - yc_key

volumes:
  config:
  proxy_config:

secrets:
  yc_id:
    file: "/usr/share/docker-secrets/YC_BACKUP_ID"
  yc_key:
    file: "/usr/share/docker-secrets/YC_BACKUP_KEY"
```

**Log output**
```
time=2025-05-04T22:32:00.097Z level=INFO msg="Now running script on schedule */1 * * * *"

time=2025-05-04T22:32:00.114Z level=INFO msg="Created backup of `/backup` at `/tmp/test-backup-2025-05-04T22-32-00.tar.gz`."

time=2025-05-04T22:32:00.115Z level=INFO msg="Removed tar file `/tmp/test-backup-2025-05-04T22-32-00.tar.gz`."

time=2025-05-04T22:32:00.115Z level=ERROR msg="Unexpected error running schedule */1 * * * *: net/http: invalid header field value for \"Authorization\"" error="main.runScript.func4: error running script: main.(*script).copyArchive: error copying archive: s3.(*s3Storage).Copy: error uploading backup to remote storage: Get \"https://storage.example.com/bucketname/?location=\": net/http: invalid header field value for \"Authorization\""
```

**Additional context**
Version: 2.43.3
Docker Engine version: 26.1.3
