### ISSUE TITLE
filesystem permissions not backed up correctly

### ISSUE THREAD

**Issue by kzshantonu** [offen/docker-volume-backup#71]
original ownership:
<img width="408" alt="WindowsTerminal_DmHzUgqMJg" src="https://user-images.githubusercontent.com/7745374/154819139-7666a267-83fc-4987-bc4c-936ba13645b0.png">

ownership of extracted backup archive:
<img width="434" alt="WindowsTerminal_YzuVZEF77u" src="https://user-images.githubusercontent.com/7745374/154819147-1ca88db6-05be-4863-9d0f-87b8989884a0.png">

**Comment by m90** [comment]
Could you provide a reproducible example for this issue? This does not happen for the setups I use this image for so I can't really tell what is happening here judging from two screenshots. It would also be helpful to provide the information requested in the issue template https://github.com/offen/docker-volume-backup/blob/main/.github/ISSUE_TEMPLATE.md

**Comment by m90** [comment]
Is there anything special about the directories for which this happens? Could it be that these are empty for example?

**Comment by kzshantonu** [comment]
It appears that it's the opposite. Dirs with data in them get owned by root whereas empty dirs have original ownership. Container in question is a standard postgres container. Path being backed up is  `/var/lib/postgresql/data` inside container.

* **I'm submitting a ...**
  - [ x] bug report
  - [ ] feature request
  - [ ] support request

* **What is the current behavior?**

original filesystem permissions/ownership not preserved. some dirs get owned by root

* **If the current behavior is a bug, please provide the configuration and steps to reproduce and if possible a minimal demo of the problem.**

* **What is the expected behavior?**

keep original filesystem permissions/ownership

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

  - Image version: 
  - Docker version: 20.10.12
  - docker-compose version: v2.2.3
  - container: postgres:14-alpine

**Comment by kzshantonu** [comment]
I have a reproducible compose yml (trigger manually):

```yaml
version: "3.8"
services:
  db:
    image: postgres:14-alpine
    container_name: postgres_debug_q7Im
    restart: unless-stopped
    labels:
      - docker-volume-backup.stop-during-backup=db
    volumes:
      - postgres_debug_q7Im:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=1FHJMSwt0yhIN1zS7I4DilGUhThBKq0x
      - POSTGRES_USER=q7Im
      - POSTGRES_DB=q7Im
  backup:
    image: offen/docker-volume-backup:latest
    restart: always
    environment:
      BACKUP_FILENAME: "backup-%Y-%m-%dT%H-%M-%S.tar.gz"
      BACKUP_FILENAME_EXPAND: "true"
      BACKUP_LATEST_SYMLINK: "backup.latest.tar.gz"
      BACKUP_RETENTION_DAYS: "7"
      BACKUP_PRUNING_PREFIX: "backup-"
      BACKUP_STOP_CONTAINER_LABEL: "db"
    volumes:
      - postgres_debug_q7Im:/backup/my-app-backup:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /root/volbaks_debug:/archive

volumes:
  postgres_debug_q7Im:
    name: postgres_debug_q7Im
```
