### ISSUE TITLE
Prune backups doesn't seem to acknowledge AWS_S3_PATH

### ISSUE THREAD

**Issue by simboel** [offen/docker-volume-backup#90]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

* **What is the current behavior?**

When using docker-volume-backup with [Backblaze b2](https://www.backblaze.com/b2/cloud-storage.html) (Region: eu-central; following the link you can create a free 10 GiB bucket) the backup retention logic doesn't seem to acknowledge the `AWS_S3_PATH` variable. I saw this message:
```
time="2022-04-13T11:36:38Z" level=warning msg="The current configuration would delete all 4 existing remote backup(s)."
time="2022-04-13T11:36:38Z" level=warning msg="Refusing to do so, please check your configuration."
```
This indicates, that it wanted to delete all 4 "directories" in the bucket. But it should've looked into the directory specified with `AWS_S3_PATH` where there are just 1 file.

* **If the current behavior is a bug, please provide the configuration and steps to reproduce and if possible a minimal demo of the problem.**

`docker-compose.yml`:
```yml
version: '3.8'
services:
  backup:
    image: offen/docker-volume-backup:latest
    environment:
      BACKUP_RETENTION_DAYS: 7
      AWS_ENDPOINT: s3.eu-central-003.backblazeb2.com
      AWS_S3_BUCKET_NAME: <bucketName>
      AWS_ACCESS_KEY_ID: <keyId>
      AWS_SECRET_ACCESS_KEY: <applicationKey>
      AWS_S3_PATH: mypath
    volumes:
      - testdata:/backup/testdata-backup:ro
volumes:
 testdata:
```

* **What is the expected behavior?**

Executing: `docker-compose up -d` & `docker-compose exec backup backup` I would expect the following structure on an **empty** bucket. **This works as epxected**

```
mypath/backup-2022-04-13T12-02-46.tar.gz
```

And I would expect the output of the command to be. **This doesn't work as expected**
```
[...]
time="2022-04-13T11:52:18Z" level=info msg="None of 0 existing remote backup(s) were pruned."
[...]
```

Instead it will show this:
```
[...]
time="2022-04-13T11:48:45Z" level=warning msg="The current configuration would delete all 1 existing remote backup(s)."
time="2022-04-13T11:48:45Z" level=warning msg="Refusing to do so, please check your configuration."
[...]
```

It seems like the prune backups logic doesn't look in the path specified with `AWS_S3_PATH` but looks in the root of the bucket (if you create new folders or files at the root level the number in the message will increase). 

* **What is the motivation / use case for changing the behavior?**

This behavior is of course incorrect and potentially dangerous (the only reason why my bucket wasn't cleared is that there is a special check in the software that prevents deleting all files).

* **Please tell us about your environment:**
  
  - Image version: latest (80635b23cb46)
  - Docker version: Docker version 20.10.14, build a224086
  - docker-compose version: docker-compose version 1.29.2, build 5becea4c

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

Maybe this is a special case with the Backblaze S3 API implementation. I haven't checked with AWS etc.
